BUILD_TEST_TASK_TEMPLATE: &BUILD_TEST_TASK_TEMPLATE
  arch_check_script:
    - uname -am
  test_script: |
    script/download-libs.sh
    npm install
    node test.js

linux_amd64_task: 
  env:
    matrix:
      - IMAGE: node:12-slim
      - IMAGE: node:14-slim
      - IMAGE: node:15-slim
      - IMAGE: node:16-slim
      - IMAGE: node:18-slim
      - IMAGE: node:19-slim
      - IMAGE: node:20-slim
  container:
    image: $IMAGE
    architecture: amd64
  install_script:
    - apt update --yes && apt install --yes curl
  << : *BUILD_TEST_TASK_TEMPLATE

linux_arm64_task: 
  env:
    matrix:
      - IMAGE: node:12-slim
      - IMAGE: node:14-slim
      - IMAGE: node:15-slim
      - IMAGE: node:16-slim
      - IMAGE: node:18-slim
      - IMAGE: node:19-slim
      - IMAGE: node:20-slim
  container:
    image: $IMAGE
    architecture: arm64
  install_script:
    - apt update --yes && apt install --yes curl
  << : *BUILD_TEST_TASK_TEMPLATE


macosx_x86_task:
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-base:latest
  env:
    PATH: ${HOME}/.nvs:${PATH}
    matrix:
      - NODE_VERSION: 12
      - NODE_VERSION: 14
      - NODE_VERSION: 15
      - NODE_VERSION: 16
      - NODE_VERSION: 18
      - NODE_VERSION: 19
      - NODE_VERSION: 20
  install_script: |
    softwareupdate --install-rosetta --agree-to-license
    git clone https://github.com/jasongin/nvs "$NVS_HOME"
    arch -x86_64 . "$NVS_HOME/nvs.sh" install
    arch -x86_64 nvs add ${NODE_VERSION}
    arch -x86_64 nvs use ${NODE_VERSION}
    arch -x86_64 node --version
  << : *BUILD_TEST_TASK_TEMPLATE
  <<< : *BUILD_TEST_TASK_TEMPLATE

windows_task:
  windows_container:
    image: cirrusci/windowsservercore:2019
  env:
    matrix:
      - NODE_VERSION: 12
      - NODE_VERSION: 14
      - NODE_VERSION: 15
      - NODE_VERSION: 16
      - NODE_VERSION: 18
      - NODE_VERSION: 19
      - NODE_VERSION: 20
  install_script: |
    choco install nvs
    nvs add ${NODE_VERSION}
    nvs use ${NODE_VERSION}
    node --version
  << : *BUILD_TEST_TASK_TEMPLATE

freebsd_task:
  freebsd_instance:
    image_family: freebsd-13-0
  env:
    PATH: ${HOME}/.nvs:${PATH}
    matrix:
      - NODE_VERSION: 12
      - NODE_VERSION: 14
      - NODE_VERSION: 15
      - NODE_VERSION: 16
      - NODE_VERSION: 18
      - NODE_VERSION: 19
      - NODE_VERSION: 20
  install_script: |
    pkg update && pkg upgrade
    pkg install curl
    git clone https://github.com/jasongin/nvs "$NVS_HOME"
    arch -x86_64 . "$NVS_HOME/nvs.sh" install
    nvs add ${NODE_VERSION}
    nvs use ${NODE_VERSION}
    node --version
  << : *BUILD_TEST_TASK_TEMPLATE



