import path from 'path';
console.log({ arch: process.arch, platform: process.platform });
const libPath = path.join(
__dirname,
'ffi',
`${process.platform}-${process.arch}`,
`${process.platform !== 'win32' ? 'lib' : ''}pact_ffi.${
  process.platform === 'win32'
    ? 'dll'
    : process.platform === 'darwin'
    ? 'dylib'
    : 'so'
}`);
console.log('libPath', libPath);
import koffi from 'koffi';
import {PactFfi} from './types';
const lib = koffi.load(libPath);

// const VerifierHandle = koffi.struct('VerifierHandle', {
//   tv_sec: 'unsigned int',
// });

const VerifierHandle = koffi.opaque('VerifierHandle');

export const PactKoffi = () => {
  return  {
    version: lib.func("pactffi_version", "string", []),
    init: lib.func("pactffi_init", "void", ["string"]),
    initWithLogLevel: lib.func("pactffi_init_with_log_level", "void", ["string"]),
    enableAnsiSupport: lib.func("pactffi_enable_ansi_support", "void", []),
    logMessage: lib.func("pactffi_log_message", "void", ["string", "string", "string"]),
    matchMessage: lib.func("pactffi_match_message", "string", ["string", "string"]),
    mismatchesGetIter: lib.func("pactffi_mismatches_get_iter", "string", ["string"]),
    mismatchesDelete: lib.func("pactffi_mismatches_delete", "void", ["string"]),
    mismatchesIterNext: lib.func("pactffi_mismatches_iter_next", "string", ["string"]),
    mismatchesIterDelete: lib.func("pactffi_mismatches_iter_delete", "void", ["string"]),
    mismatchToJson: lib.func("pactffi_mismatch_to_json", "string", ["string"]),
    mismatchType: lib.func("pactffi_mismatch_type", "string", ["string"]),
    mismatchSummary: lib.func("pactffi_mismatch_summary", "string", ["string"]),
    mismatchDescription: lib.func("pactffi_mismatch_description", "string", ["string"]),
    mismatchAnsiDescription: lib.func("pactffi_mismatch_ansi_description", "string", ["string"]),
    getErrorMessage: lib.func("pactffi_get_error_message", "int32", ["string", "int32"]),
    logToStdout: lib.func("pactffi_log_to_stdout", "int32", ["int32"]),
    logToStderr: lib.func("pactffi_log_to_stderr", "int32", ["int32"]),
    logToFile: lib.func("pactffi_log_to_file", "int32", ["string", "int32"]),
    logToBuffer: lib.func("pactffi_log_to_buffer", "int32", ["int32"]),
    loggerInit: lib.func("pactffi_logger_init", "void", []),
    loggerAttachSink: lib.func("pactffi_logger_attach_sink", "int32", ["string", "int32"]),
    loggerApply: lib.func("pactffi_logger_apply", "int32", []),
    fetchLogBuffer: lib.func("pactffi_fetch_log_buffer", "string", ["string"]),
    parsePactJson: lib.func("pactffi_parse_pact_json", "string", ["string"]),
    pactModelDelete: lib.func("pactffi_pact_model_delete", "void", ["string"]),
    pactModelInteractionIterator: lib.func("pactffi_pact_model_interaction_iterator", "string", ["string"]),
    pactSpecVersion: lib.func("pactffi_pact_spec_version", "int32", ["string"]),
    pactInteractionDelete: lib.func("pactffi_pact_interaction_delete", "void", ["string"]),
    asyncMessageNew: lib.func("pactffi_async_message_new", "string", []),
    asyncMessageDelete: lib.func("pactffi_async_message_delete", "void", ["string"]),
    asyncMessageGetContents: lib.func("pactffi_async_message_get_contents", "string", ["string"]),
    asyncMessageGetContentsStr: lib.func("pactffi_async_message_get_contents_str", "string", ["string"]),
    asyncMessageSetContentsStr: lib.func("pactffi_async_message_set_contents_str", "void", ["string", "string", "string"]),
    asyncMessageGetContentsLength: lib.func("pactffi_async_message_get_contents_length", "size_t", ["string"]),
    asyncMessageGetContentsBin: lib.func("pactffi_async_message_get_contents_bin", "string", ["string"]),
    asyncMessageSetContentsBin: lib.func("pactffi_async_message_set_contents_bin", "void", ["string", "string", "size_t", "string"]),
    asyncMessageGetDescription: lib.func("pactffi_async_message_get_description", "string", ["string"]),
    asyncMessageSetDescription: lib.func("pactffi_async_message_set_description", "int32", ["string", "string"]),
    asyncMessageGetProviderState: lib.func("pactffi_async_message_get_provider_state", "string", ["string", "uint32"]),
    asyncMessageGetProviderStateIter: lib.func("pactffi_async_message_get_provider_state_iter", "string", ["string"]),
    consumerGetName: lib.func("pactffi_consumer_get_name", "string", ["string"]),
    pactGetConsumer: lib.func("pactffi_pact_get_consumer", "string", ["string"]),
    pactConsumerDelete: lib.func("pactffi_pact_consumer_delete", "void", ["string"]),
    messageContentsGetContentsStr: lib.func("pactffi_message_contents_get_contents_str", "string", ["string"]),
    messageContentsSetContentsStr: lib.func("pactffi_message_contents_set_contents_str", "void", ["string", "string", "string"]),
    messageContentsGetContentsLength: lib.func("pactffi_message_contents_get_contents_length", "size_t", ["string"]),
    messageContentsGetContentsBin: lib.func("pactffi_message_contents_get_contents_bin", "string", ["string"]),
    messageContentsSetContentsBin: lib.func("pactffi_message_contents_set_contents_bin", "void", ["string", "string", "size_t", "string"]),
    messageContentsGetMetadataIter: lib.func("pactffi_message_contents_get_metadata_iter", "string", ["string"]),
    messageContentsGetMatchingRuleIter: lib.func("pactffi_message_contents_get_matching_rule_iter", "string", ["string", "int32"]),
    requestContentsGetMatchingRuleIter: lib.func("pactffi_request_contents_get_matching_rule_iter", "string", ["string", "int32"]),
    responseContentsGetMatchingRuleIter: lib.func("pactffi_response_contents_get_matching_rule_iter", "string", ["string", "int32"]),
    messageContentsGetGeneratorsIter: lib.func("pactffi_message_contents_get_generators_iter", "string", ["string", "int32"]),
    requestContentsGetGeneratorsIter: lib.func("pactffi_request_contents_get_generators_iter", "string", ["string", "int32"]),
    responseContentsGetGeneratorsIter: lib.func("pactffi_response_contents_get_generators_iter", "string", ["string", "int32"]),
    parseMatcherDefinition: lib.func("pactffi_parse_matcher_definition", "string", ["string"]),
    matcherDefinitionError: lib.func("pactffi_matcher_definition_error", "string", ["string"]),
    matcherDefinitionValue: lib.func("pactffi_matcher_definition_value", "string", ["string"]),
    matcherDefinitionDelete: lib.func("pactffi_matcher_definition_delete", "void", ["string"]),
    matcherDefinitionGenerator: lib.func("pactffi_matcher_definition_generator", "string", ["string"]),
    matcherDefinitionValueType: lib.func("pactffi_matcher_definition_value_type", "int32", ["string"]),
    matchingRuleIterDelete: lib.func("pactffi_matching_rule_iter_delete", "void", ["string"]),
    matcherDefinitionIter: lib.func("pactffi_matcher_definition_iter", "string", ["string"]),
    matchingRuleIterNext: lib.func("pactffi_matching_rule_iter_next", "string", ["string"]),
    matchingRuleId: lib.func("pactffi_matching_rule_id", "uint16", ["string"]),
    matchingRuleValue: lib.func("pactffi_matching_rule_value", "string", ["string"]),
    matchingRulePointer: lib.func("pactffi_matching_rule_pointer", "string", ["string"]),
    matchingRuleReferenceName: lib.func("pactffi_matching_rule_reference_name", "string", ["string"]),
    validateDatetime: lib.func("pactffi_validate_datetime", "int32", ["string", "string"]),
    generatorToJson: lib.func("pactffi_generator_to_json", "string", ["string"]),
    generatorGenerateString: lib.func("pactffi_generator_generate_string", "string", ["string", "string"]),
    generatorGenerateInteger: lib.func("pactffi_generator_generate_integer", "uint16", ["string", "string"]),
    generatorsIterDelete: lib.func("pactffi_generators_iter_delete", "void", ["string"]),
    generatorsIterNext: lib.func("pactffi_generators_iter_next", "string", ["string"]),
    generatorsIterPairDelete: lib.func("pactffi_generators_iter_pair_delete", "void", ["string"]),
    syncHttpNew: lib.func("pactffi_sync_http_new", "string", []),
    syncHttpDelete: lib.func("pactffi_sync_http_delete", "void", ["string"]),
    syncHttpGetRequest: lib.func("pactffi_sync_http_get_request", "string", ["string"]),
    syncHttpGetRequestContents: lib.func("pactffi_sync_http_get_request_contents", "string", ["string"]),
    syncHttpSetRequestContents: lib.func("pactffi_sync_http_set_request_contents", "void", ["string", "string", "string"]),
    syncHttpGetRequestContentsLength: lib.func("pactffi_sync_http_get_request_contents_length", "size_t", ["string"]),
    syncHttpGetRequestContentsBin: lib.func("pactffi_sync_http_get_request_contents_bin", "string", ["string"]),
    syncHttpSetRequestContentsBin: lib.func("pactffi_sync_http_set_request_contents_bin", "void", ["string", "string", "size_t", "string"]),
    syncHttpGetResponse: lib.func("pactffi_sync_http_get_response", "string", ["string"]),
    syncHttpGetResponseContents: lib.func("pactffi_sync_http_get_response_contents", "string", ["string"]),
    syncHttpSetResponseContents: lib.func("pactffi_sync_http_set_response_contents", "void", ["string", "string", "string"]),
    syncHttpGetResponseContentsLength: lib.func("pactffi_sync_http_get_response_contents_length", "size_t", ["string"]),
    syncHttpGetResponseContentsBin: lib.func("pactffi_sync_http_get_response_contents_bin", "string", ["string"]),
    syncHttpSetResponseContentsBin: lib.func("pactffi_sync_http_set_response_contents_bin", "void", ["string", "string", "size_t", "string"]),
    syncHttpGetDescription: lib.func("pactffi_sync_http_get_description", "string", ["string"]),
    syncHttpSetDescription: lib.func("pactffi_sync_http_set_description", "int32", ["string", "string"]),
    syncHttpGetProviderState: lib.func("pactffi_sync_http_get_provider_state", "string", ["string", "uint32"]),
    syncHttpGetProviderStateIter: lib.func("pactffi_sync_http_get_provider_state_iter", "string", ["string"]),
    pactInteractionAsSynchronousHttp: lib.func("pactffi_pact_interaction_as_synchronous_http", "string", ["string"]),
    pactInteractionAsMessage: lib.func("pactffi_pact_interaction_as_message", "string", ["string"]),
    pactInteractionAsAsynchronousMessage: lib.func("pactffi_pact_interaction_as_asynchronous_message", "string", ["string"]),
    pactInteractionAsSynchronousMessage: lib.func("pactffi_pact_interaction_as_synchronous_message", "string", ["string"]),
    pactMessageIterDelete: lib.func("pactffi_pact_message_iter_delete", "void", ["string"]),
    pactMessageIterNext: lib.func("pactffi_pact_message_iter_next", "string", ["string"]),
    pactSyncMessageIterNext: lib.func("pactffi_pact_sync_message_iter_next", "string", ["string"]),
    pactSyncMessageIterDelete: lib.func("pactffi_pact_sync_message_iter_delete", "void", ["string"]),
    pactSyncHttpIterNext: lib.func("pactffi_pact_sync_http_iter_next", "string", ["string"]),
    pactSyncHttpIterDelete: lib.func("pactffi_pact_sync_http_iter_delete", "void", ["string"]),
    pactInteractionIterNext: lib.func("pactffi_pact_interaction_iter_next", "string", ["string"]),
    pactInteractionIterDelete: lib.func("pactffi_pact_interaction_iter_delete", "void", ["string"]),
    matchingRuleToJson: lib.func("pactffi_matching_rule_to_json", "string", ["string"]),
    matchingRulesIterDelete: lib.func("pactffi_matching_rules_iter_delete", "void", ["string"]),
    matchingRulesIterNext: lib.func("pactffi_matching_rules_iter_next", "string", ["string"]),
    matchingRulesIterPairDelete: lib.func("pactffi_matching_rules_iter_pair_delete", "void", ["string"]),
    messageNew: lib.func("pactffi_message_new", "string", []),
    messageNewFromJson: lib.func("pactffi_message_new_from_json", "string", ["uint32", "string", "int32"]),
    messageNewFromBody: lib.func("pactffi_message_new_from_body", "string", ["string", "string"]),
    messageDelete: lib.func("pactffi_message_delete", "void", ["string"]),
    messageGetContents: lib.func("pactffi_message_get_contents", "string", ["string"]),
    messageSetContents: lib.func("pactffi_message_set_contents", "void", ["string", "string", "string"]),
    messageGetContentsLength: lib.func("pactffi_message_get_contents_length", "size_t", ["string"]),
    messageGetContentsBin: lib.func("pactffi_message_get_contents_bin", "string", ["string"]),
    messageSetContentsBin: lib.func("pactffi_message_set_contents_bin", "void", ["string", "string", "size_t", "string"]),
    messageGetDescription: lib.func("pactffi_message_get_description", "string", ["string"]),
    messageSetDescription: lib.func("pactffi_message_set_description", "int32", ["string", "string"]),
    messageGetProviderState: lib.func("pactffi_message_get_provider_state", "string", ["string", "uint32"]),
    messageGetProviderStateIter: lib.func("pactffi_message_get_provider_state_iter", "string", ["string"]),
    providerStateIterNext: lib.func("pactffi_provider_state_iter_next", "string", ["string"]),
    providerStateIterDelete: lib.func("pactffi_provider_state_iter_delete", "void", ["string"]),
    messageFindMetadata: lib.func("pactffi_message_find_metadata", "string", ["string", "string"]),
    messageInsertMetadata: lib.func("pactffi_message_insert_metadata", "int32", ["string", "string", "string"]),
    messageMetadataIterNext: lib.func("pactffi_message_metadata_iter_next", "string", ["string"]),
    messageGetMetadataIter: lib.func("pactffi_message_get_metadata_iter", "string", ["string"]),
    messageMetadataIterDelete: lib.func("pactffi_message_metadata_iter_delete", "void", ["string"]),
    messageMetadataPairDelete: lib.func("pactffi_message_metadata_pair_delete", "void", ["string"]),
    messagePactNewFromJson: lib.func("pactffi_message_pact_new_from_json", "string", ["string", "string"]),
    messagePactDelete: lib.func("pactffi_message_pact_delete", "void", ["string"]),
    messagePactGetConsumer: lib.func("pactffi_message_pact_get_consumer", "string", ["string"]),
    messagePactGetProvider: lib.func("pactffi_message_pact_get_provider", "string", ["string"]),
    messagePactGetMessageIter: lib.func("pactffi_message_pact_get_message_iter", "string", ["string"]),
    messagePactMessageIterNext: lib.func("pactffi_message_pact_message_iter_next", "string", ["string"]),
    messagePactMessageIterDelete: lib.func("pactffi_message_pact_message_iter_delete", "void", ["string"]),
    messagePactFindMetadata: lib.func("pactffi_message_pact_find_metadata", "string", ["string", "string", "string"]),
    messagePactGetMetadataIter: lib.func("pactffi_message_pact_get_metadata_iter", "string", ["string"]),
    messagePactMetadataIterNext: lib.func("pactffi_message_pact_metadata_iter_next", "string", ["string"]),
    messagePactMetadataIterDelete: lib.func("pactffi_message_pact_metadata_iter_delete", "void", ["string"]),
    messagePactMetadataTripleDelete: lib.func("pactffi_message_pact_metadata_triple_delete", "void", ["string"]),
    providerGetName: lib.func("pactffi_provider_get_name", "string", ["string"]),
    pactGetProvider: lib.func("pactffi_pact_get_provider", "string", ["string"]),
    pactProviderDelete: lib.func("pactffi_pact_provider_delete", "void", ["string"]),
    providerStateGetName: lib.func("pactffi_provider_state_get_name", "string", ["string"]),
    providerStateGetParamIter: lib.func("pactffi_provider_state_get_param_iter", "string", ["string"]),
    providerStateParamIterNext: lib.func("pactffi_provider_state_param_iter_next", "string", ["string"]),
    providerStateDelete: lib.func("pactffi_provider_state_delete", "void", ["string"]),
    providerStateParamIterDelete: lib.func("pactffi_provider_state_param_iter_delete", "void", ["string"]),
    providerStateParamPairDelete: lib.func("pactffi_provider_state_param_pair_delete", "void", ["string"]),
    syncMessageNew: lib.func("pactffi_sync_message_new", "string", []),
    syncMessageDelete: lib.func("pactffi_sync_message_delete", "void", ["string"]),
    syncMessageGetRequestContentsStr: lib.func("pactffi_sync_message_get_request_contents_str", "string", ["string"]),
    syncMessageSetRequestContentsStr: lib.func("pactffi_sync_message_set_request_contents_str", "void", ["string", "string", "string"]),
    syncMessageGetRequestContentsLength: lib.func("pactffi_sync_message_get_request_contents_length", "size_t", ["string"]),
    syncMessageGetRequestContentsBin: lib.func("pactffi_sync_message_get_request_contents_bin", "string", ["string"]),
    syncMessageSetRequestContentsBin: lib.func("pactffi_sync_message_set_request_contents_bin", "void", ["string", "string", "size_t", "string"]),
    syncMessageGetRequestContents: lib.func("pactffi_sync_message_get_request_contents", "string", ["string"]),
    syncMessageGetNumberResponses: lib.func("pactffi_sync_message_get_number_responses", "size_t", ["string"]),
    syncMessageGetResponseContentsStr: lib.func("pactffi_sync_message_get_response_contents_str", "string", ["string", "size_t"]),
    syncMessageSetResponseContentsStr: lib.func("pactffi_sync_message_set_response_contents_str", "void", ["string", "size_t", "string", "string"]),
    syncMessageGetResponseContentsLength: lib.func("pactffi_sync_message_get_response_contents_length", "size_t", ["string", "size_t"]),
    syncMessageGetResponseContentsBin: lib.func("pactffi_sync_message_get_response_contents_bin", "string", ["string", "size_t"]),
    syncMessageSetResponseContentsBin: lib.func("pactffi_sync_message_set_response_contents_bin", "void", ["string", "size_t", "string", "size_t", "string"]),
    syncMessageGetResponseContents: lib.func("pactffi_sync_message_get_response_contents", "string", ["string", "size_t"]),
    syncMessageGetDescription: lib.func("pactffi_sync_message_get_description", "string", ["string"]),
    syncMessageSetDescription: lib.func("pactffi_sync_message_set_description", "int32", ["string", "string"]),
    syncMessageGetProviderState: lib.func("pactffi_sync_message_get_provider_state", "string", ["string", "uint32"]),
    syncMessageGetProviderStateIter: lib.func("pactffi_sync_message_get_provider_state_iter", "string", ["string"]),
    stringDelete: lib.func("pactffi_string_delete", "void", ["string"]),
    createMockServer: lib.func("pactffi_create_mock_server", "int32", ["string", "string", "uint8"]),
    getTlsCaCertificate: lib.func("pactffi_get_tls_ca_certificate", "string", []),
    createMockServerForPact: lib.func("pactffi_create_mock_server_for_pact", "int32", ["uint16", "string", "uint8"]),
    createMockServerForTransport: lib.func("pactffi_create_mock_server_for_transport", "int32", ["uint16", "string", "uint16", "string", "string"]),
    mockServerMatched: lib.func("pactffi_mock_server_matched", "uint8", ["int32"]),
    mockServerMismatches: lib.func("pactffi_mock_server_mismatches", "string", ["int32"]),
    cleanupMockServer: lib.func("pactffi_cleanup_mock_server", "uint8", ["int32"]),
    writePactFile: lib.func("pactffi_write_pact_file", "int32", ["int32", "string", "uint8"]),
    mockServerLogs: lib.func("pactffi_mock_server_logs", "string", ["int32"]),
    generateDatetimeString: lib.func("pactffi_generate_datetime_string", "string", ["string"]),
    checkRegex: lib.func("pactffi_check_regex", "uint8", ["string", "string"]),
    generateRegexValue: lib.func("pactffi_generate_regex_value", "string", ["string"]),
    freeString: lib.func("pactffi_free_string", "void", ["string"]),
    newPact: lib.func("pactffi_new_pact", "uint16", ["string", "string"]),
    newInteraction: lib.func("pactffi_new_interaction", "uint32", ["uint16", "string"]),
    newMessageInteraction: lib.func("pactffi_new_message_interaction", "uint32", ["uint16", "string"]),
    newSyncMessageInteraction: lib.func("pactffi_new_sync_message_interaction", "uint32", ["uint16", "string"]),
    uponReceiving: lib.func("pactffi_upon_receiving", "uint8", ["uint32", "string"]),
    given: lib.func("pactffi_given", "uint8", ["uint32", "string"]),
    interactionTestName: lib.func("pactffi_interaction_test_name", "uint32", ["uint32", "string"]),
    givenWithParam: lib.func("pactffi_given_with_param", "uint8", ["uint32", "string", "string", "string"]),
    withRequest: lib.func("pactffi_with_request", "uint8", ["uint32", "string", "string"]),
    withQueryParameter: lib.func("pactffi_with_query_parameter", "uint8", ["uint32", "string", "size_t", "string"]),
    withQueryParameterV2: lib.func("pactffi_with_query_parameter_v2", "uint8", ["uint32", "string", "size_t", "string"]),
    withSpecification: lib.func("pactffi_with_specification", "uint8", ["uint16", "int32"]),
    withPactMetadata: lib.func("pactffi_with_pact_metadata", "uint8", ["uint16", "string", "string", "string"]),
    withHeader: lib.func("pactffi_with_header", "uint8", ["uint32", "int32", "string", "size_t", "string"]),
    withHeaderV2: lib.func("pactffi_with_header_v2", "uint8", ["uint32", "int32", "string", "size_t", "string"]),
    responseStatus: lib.func("pactffi_response_status", "uint8", ["uint32", "uint16"]),
    withBody: lib.func("pactffi_with_body", "uint8", ["uint32", "int32", "string", "string"]),
    withBinaryFile: lib.func("pactffi_with_binary_file", "uint8", ["uint32", "int32", "string", "string", "size_t"]),
    withMultipartFile: lib.func("pactffi_with_multipart_file", "string", ["uint32", "int32", "string", "string", "string"]),
    pactHandleGetMessageIter: lib.func("pactffi_pact_handle_get_message_iter", "string", ["uint16"]),
    pactHandleGetSyncMessageIter: lib.func("pactffi_pact_handle_get_sync_message_iter", "string", ["uint16"]),
    pactHandleGetSyncHttpIter: lib.func("pactffi_pact_handle_get_sync_http_iter", "string", ["uint16"]),
    newMessagePact: lib.func("pactffi_new_message_pact", "uint16", ["string", "string"]),
    newMessage: lib.func("pactffi_new_message", "uint32", ["uint16", "string"]),
    messageExpectsToReceive: lib.func("pactffi_message_expects_to_receive", "void", ["uint32", "string"]),
    messageGiven: lib.func("pactffi_message_given", "void", ["uint32", "string"]),
    messageGivenWithParam: lib.func("pactffi_message_given_with_param", "void", ["uint32", "string", "string", "string"]),
    messageWithContents: lib.func("pactffi_message_with_contents", "void", ["uint32", "string", "string", "size_t"]),
    messageWithMetadata: lib.func("pactffi_message_with_metadata", "void", ["uint32", "string", "string"]),
    messageReify: lib.func("pactffi_message_reify", "string", ["uint32"]),
    writeMessagePactFile: lib.func("pactffi_write_message_pact_file", "int32", ["uint16", "string", "uint8"]),
    withMessagePactMetadata: lib.func("pactffi_with_message_pact_metadata", "void", ["uint16", "string", "string", "string"]),
    pactHandleWriteFile: lib.func("pactffi_pact_handle_write_file", "int32", ["uint16", "string", "uint8"]),
    newAsyncMessage: lib.func("pactffi_new_async_message", "uint32", ["uint16", "string"]),
    freePactHandle: lib.func("pactffi_free_pact_handle", "uint32", ["uint16"]),
    freeMessagePactHandle: lib.func("pactffi_free_message_pact_handle", "uint32", ["uint16"]),
    verify: lib.func("pactffi_verify", "int32", ["string"]),
    verifierNew: lib.func("pactffi_verifier_new", koffi.pointer(VerifierHandle), []),
    verifierNewForApplication: lib.func("pactffi_verifier_new_for_application", koffi.pointer(VerifierHandle), ["string", "string"]),
    verifierShutdown: lib.func("pactffi_verifier_shutdown", "void", [koffi.pointer(VerifierHandle)]),
    verifierSetProviderInfo: lib.func("pactffi_verifier_set_provider_info", "void", [koffi.pointer(VerifierHandle), "string", "string", "string", "uint16", "string"]),
    verifierAddProviderTransport: lib.func("pactffi_verifier_add_provider_transport", "void", ["string", "string", "uint16", "string", "string"]),
    verifierSetFilterInfo: lib.func("pactffi_verifier_set_filter_info", "void", ["string", "string", "string", "uint8"]),
    verifierSetProviderState: lib.func("pactffi_verifier_set_provider_state", "void", ["string", "string", "uint8", "uint8"]),
    verifierSetVerificationOptions: lib.func("pactffi_verifier_set_verification_options", "int32", ["string", "uint8", "uint64"]),
    verifierSetColouredOutput: lib.func("pactffi_verifier_set_coloured_output", "int32", ["string", "uint8"]),
    verifierSetNoPactsIsError: lib.func("pactffi_verifier_set_no_pacts_is_error", "int32", ["string", "uint8"]),
    verifierSetPublishOptions: lib.func("pactffi_verifier_set_publish_options", "int32", ["string", "string", "string", "string", "uint16", "string"]),
    verifierSetConsumerFilters: lib.func("pactffi_verifier_set_consumer_filters", "void", ["string", "string", "uint16"]),
    verifierAddCustomHeader: lib.func("pactffi_verifier_add_custom_header", "void", ["string", "string", "string"]),
    verifierAddFileSource: lib.func("pactffi_verifier_add_file_source", "void", ["string", "string"]),
    verifierAddDirectorySource: lib.func("pactffi_verifier_add_directory_source", "void", ["string", "string"]),
    verifierUrlSource: lib.func("pactffi_verifier_url_source", "void", ["string", "string", "string", "string", "string"]),
    verifierBrokerSource: lib.func("pactffi_verifier_broker_source", "void", ["string", "string", "string", "string", "string"]),
    verifierBrokerSourceWithSelectors: lib.func("pactffi_verifier_broker_source_with_selectors", "void", ["string", "string", "string", "string", "string", "uint8", "string", "string", "uint16", "string", "string", "uint16", "string", "uint16"]),
    verifierExecute: lib.func("pactffi_verifier_execute", "int32", ["string"]),
    verifierCliArgs: lib.func("pactffi_verifier_cli_args", "string", []),
    verifierLogs: lib.func("pactffi_verifier_logs", "string", ["string"]),
    verifierLogsForProvider: lib.func("pactffi_verifier_logs_for_provider", "string", ["string"]),
    verifierOutput: lib.func("pactffi_verifier_output", "string", ["string", "uint8"]),
    verifierJson: lib.func("pactffi_verifier_json", "string", ["string"]),
    usingPlugin: lib.func("pactffi_using_plugin", "uint32", ["uint16", "string", "string"]),
    cleanupPlugins: lib.func("pactffi_cleanup_plugins", "void", ["uint16"]),
    interactionContents: lib.func("pactffi_interaction_contents", "uint32", ["uint32", "int32", "string", "string"]),
    matchesStringValue: lib.func("pactffi_matches_string_value", "string", ["string", "string", "string", "uint8"]),
    matchesU64Value: lib.func("pactffi_matches_u64_value", "string", ["string", "uint64", "uint64", "uint8"]),
    matchesI64Value: lib.func("pactffi_matches_i64_value", "string", ["string", "int64", "int64", "uint8"]),
    matchesF64Value: lib.func("pactffi_matches_f64_value", "string", ["string", "double", "double", "uint8"]),
    matchesBoolValue: lib.func("pactffi_matches_bool_value", "string", ["string", "uint8", "uint8", "uint8"]),
    matchesBinaryValue: lib.func("pactffi_matches_binary_value", "string", ["string", "string", "uint64", "string", "uint64", "uint8"]),
    matchesJsonValue: lib.func("pactffi_matches_json_value", "string", ["string", "string", "string", "uint8"])  
    } as unknown as typeof PactFfi
  } 
console.log(`Hello Ffi!\n ${PactKoffi().version()}`);  