import path from 'path';
console.log({ arch: process.arch, platform: process.platform });
const libPath = path.join(
__dirname,
'ffi',
`${process.platform}-${process.arch}`,
`${process.platform !== 'win32' ? 'lib' : ''}pact_ffi.${
  process.platform === 'win32'
    ? 'dll'
    : process.platform === 'darwin'
    ? 'dylib'
    : 'so'
}`);
console.log('libPath', libPath);
import koffi from 'koffi';
import {PactFfi} from './types';
const lib = koffi.load(libPath);

const Mismatches = koffi.opaque("Mismatches")
const MismatchesIterator = koffi.opaque("MismatchesIterator")
const Mismatch = koffi.opaque("Mismatch")
const PactInteractionIterator = koffi.opaque("PactInteractionIterator")
const AsynchronousMessage = koffi.opaque("AsynchronousMessage")
const MessageContents = koffi.opaque("MessageContents")
const ProviderState = koffi.opaque("ProviderState")
const ProviderStateIterator = koffi.opaque("ProviderStateIterator")
const Consumer = koffi.opaque("Consumer")
const MessageMetadataIterator = koffi.opaque("MessageMetadataIterator")
const MatchingRuleDefinitionResult = koffi.opaque("MatchingRuleDefinitionResult")
const Generator = koffi.opaque("Generator")
const MatchingRuleIterator = koffi.opaque("MatchingRuleIterator")
const MatchingRuleResult = koffi.opaque("MatchingRuleResult")
const MatchingRule = koffi.opaque("MatchingRule")
const SynchronousHttp = koffi.opaque("SynchronousHttp")
const HttpRequest = koffi.opaque("HttpRequest")
const HttpResponse = koffi.opaque("HttpResponse")
const PactInteraction = koffi.opaque("PactInteraction")
const MessagePact = koffi.opaque("MessagePact")
const Provider = koffi.opaque("Provider")
const Message = koffi.opaque("Message")
const Pact = koffi.opaque("Pact")
const MessagePactMessageIterator = koffi.opaque("MessagePactMessageIterator")
const MessagePactMetadataIterator = koffi.opaque("MessagePactMetadataIterator")
const ProviderStateParamIterator = koffi.opaque("ProviderStateParamIterator")
const PactMessageIterator = koffi.opaque("PactMessageIterator")
const PactSyncMessageIterator = koffi.opaque("PactSyncMessageIterator")
const PactSyncHttpIterator = koffi.opaque("PactSyncHttpIterator")
const MatchingRuleCategoryIterator = koffi.opaque("MatchingRuleCategoryIterator")
const GeneratorCategoryIterator = koffi.opaque("GeneratorCategoryIterator")
const SynchronousMessage = koffi.opaque("SynchronousMessage")
const VerifierHandle = koffi.opaque("VerifierHandle")

export const PactKoffi = () => {
  return  {
    version: lib.func("pactffi_version", "string", []),
    init: lib.func("pactffi_init", "void", ["string"]),
    initWithLogLevel: lib.func("pactffi_init_with_log_level", "void", ["string"]),
    enableAnsiSupport: lib.func("pactffi_enable_ansi_support", "void", []),
    logMessage: lib.func("pactffi_log_message", "void", ["string", "string", "string"]),
    matchMessage: lib.func("pactffi_match_message", koffi.pointer("Mismatches"), [koffi.pointer("Message"), koffi.pointer("Message")]),
    mismatchesGetIter: lib.func("pactffi_mismatches_get_iter", koffi.pointer("MismatchesIterator"), [koffi.pointer("Mismatches")]),
    mismatchesDelete: lib.func("pactffi_mismatches_delete", "void", [koffi.pointer("Mismatches")]),
    mismatchesIterNext: lib.func("pactffi_mismatches_iter_next", koffi.pointer("Mismatch"), [koffi.pointer("MismatchesIterator")]),
    mismatchesIterDelete: lib.func("pactffi_mismatches_iter_delete", "void", [koffi.pointer("MismatchesIterator")]),
    mismatchToJson: lib.func("pactffi_mismatch_to_json", "string", [koffi.pointer("Mismatch")]),
    mismatchType: lib.func("pactffi_mismatch_type", "string", [koffi.pointer("Mismatch")]),
    mismatchSummary: lib.func("pactffi_mismatch_summary", "string", [koffi.pointer("Mismatch")]),
    mismatchDescription: lib.func("pactffi_mismatch_description", "string", [koffi.pointer("Mismatch")]),
    mismatchAnsiDescription: lib.func("pactffi_mismatch_ansi_description", "string", [koffi.pointer("Mismatch")]),
    getErrorMessage: lib.func("pactffi_get_error_message", "int32", ["string", "int32"]),
    logToStdout: lib.func("pactffi_log_to_stdout", "int32", ["int32"]),
    logToStderr: lib.func("pactffi_log_to_stderr", "int32", ["int32"]),
    logToFile: lib.func("pactffi_log_to_file", "int32", ["string", "int32"]),
    logToBuffer: lib.func("pactffi_log_to_buffer", "int32", ["int32"]),
    loggerInit: lib.func("pactffi_logger_init", "void", []),
    loggerAttachSink: lib.func("pactffi_logger_attach_sink", "int32", ["string", "int32"]),
    loggerApply: lib.func("pactffi_logger_apply", "int32", []),
    fetchLogBuffer: lib.func("pactffi_fetch_log_buffer", "string", ["string"]),
    parsePactJson: lib.func("pactffi_parse_pact_json", koffi.pointer("Pact"), ["string"]),
    pactModelDelete: lib.func("pactffi_pact_model_delete", "void", [koffi.pointer("Pact")]),
    pactModelInteractionIterator: lib.func("pactffi_pact_model_interaction_iterator", koffi.pointer("PactInteractionIterator"), [koffi.pointer("Pact")]),
    pactSpecVersion: lib.func("pactffi_pact_spec_version", "int32", [koffi.pointer("Pact")]),
    pactInteractionDelete: lib.func("pactffi_pact_interaction_delete", "void", [koffi.pointer("PactInteraction")]),
    asyncMessageNew: lib.func("pactffi_async_message_new", koffi.pointer("AsynchronousMessage"), []),
    asyncMessageDelete: lib.func("pactffi_async_message_delete", "void", [koffi.pointer("AsynchronousMessage")]),
    asyncMessageGetContents: lib.func("pactffi_async_message_get_contents", koffi.pointer("MessageContents"), [koffi.pointer("AsynchronousMessage")]),
    asyncMessageGetContentsStr: lib.func("pactffi_async_message_get_contents_str", "string", [koffi.pointer("AsynchronousMessage")]),
    asyncMessageSetContentsStr: lib.func("pactffi_async_message_set_contents_str", "void", [koffi.pointer("AsynchronousMessage"), "string", "string"]),
    asyncMessageGetContentsLength: lib.func("pactffi_async_message_get_contents_length", "size_t", [koffi.pointer("AsynchronousMessage")]),
    asyncMessageGetContentsBin: lib.func("pactffi_async_message_get_contents_bin", "uint8", [koffi.pointer("AsynchronousMessage")]),
    asyncMessageSetContentsBin: lib.func("pactffi_async_message_set_contents_bin", "void", [koffi.pointer("AsynchronousMessage"), "uint8", "size_t", "string"]),
    asyncMessageGetDescription: lib.func("pactffi_async_message_get_description", "string", [koffi.pointer("AsynchronousMessage")]),
    asyncMessageSetDescription: lib.func("pactffi_async_message_set_description", "int32", [koffi.pointer("AsynchronousMessage"), "string"]),
    asyncMessageGetProviderState: lib.func("pactffi_async_message_get_provider_state", koffi.pointer("ProviderState"), [koffi.pointer("AsynchronousMessage"), "uint32"]),
    asyncMessageGetProviderStateIter: lib.func("pactffi_async_message_get_provider_state_iter", koffi.pointer("ProviderStateIterator"), [koffi.pointer("AsynchronousMessage")]),
    consumerGetName: lib.func("pactffi_consumer_get_name", "string", [koffi.pointer("Consumer")]),
    pactGetConsumer: lib.func("pactffi_pact_get_consumer", koffi.pointer("Consumer"), [koffi.pointer("Pact")]),
    pactConsumerDelete: lib.func("pactffi_pact_consumer_delete", "void", [koffi.pointer("Consumer")]),
    messageContentsGetContentsStr: lib.func("pactffi_message_contents_get_contents_str", "string", [koffi.pointer("MessageContents")]),
    messageContentsSetContentsStr: lib.func("pactffi_message_contents_set_contents_str", "void", [koffi.pointer("MessageContents"), "string", "string"]),
    messageContentsGetContentsLength: lib.func("pactffi_message_contents_get_contents_length", "size_t", [koffi.pointer("MessageContents")]),
    messageContentsGetContentsBin: lib.func("pactffi_message_contents_get_contents_bin", "uint8", [koffi.pointer("MessageContents")]),
    messageContentsSetContentsBin: lib.func("pactffi_message_contents_set_contents_bin", "void", [koffi.pointer("MessageContents"), "uint8", "size_t", "string"]),
    messageContentsGetMetadataIter: lib.func("pactffi_message_contents_get_metadata_iter", koffi.pointer("MessageMetadataIterator"), [koffi.pointer("MessageContents")]),
    messageContentsGetMatchingRuleIter: lib.func("pactffi_message_contents_get_matching_rule_iter", koffi.pointer("MatchingRuleCategoryIterator"), [koffi.pointer("MessageContents"), "int32"]),
    requestContentsGetMatchingRuleIter: lib.func("pactffi_request_contents_get_matching_rule_iter", koffi.pointer("MatchingRuleCategoryIterator"), [koffi.pointer("HttpRequest"), "int32"]),
    responseContentsGetMatchingRuleIter: lib.func("pactffi_response_contents_get_matching_rule_iter", koffi.pointer("MatchingRuleCategoryIterator"), [koffi.pointer("HttpResponse"), "int32"]),
    messageContentsGetGeneratorsIter: lib.func("pactffi_message_contents_get_generators_iter", koffi.pointer("GeneratorCategoryIterator"), [koffi.pointer("MessageContents"), "int32"]),
    requestContentsGetGeneratorsIter: lib.func("pactffi_request_contents_get_generators_iter", koffi.pointer("GeneratorCategoryIterator"), [koffi.pointer("HttpRequest"), "int32"]),
    responseContentsGetGeneratorsIter: lib.func("pactffi_response_contents_get_generators_iter", koffi.pointer("GeneratorCategoryIterator"), [koffi.pointer("HttpResponse"), "int32"]),
    parseMatcherDefinition: lib.func("pactffi_parse_matcher_definition", koffi.pointer("MatchingRuleDefinitionResult"), ["string"]),
    matcherDefinitionError: lib.func("pactffi_matcher_definition_error", "string", [koffi.pointer("MatchingRuleDefinitionResult")]),
    matcherDefinitionValue: lib.func("pactffi_matcher_definition_value", "string", [koffi.pointer("MatchingRuleDefinitionResult")]),
    matcherDefinitionDelete: lib.func("pactffi_matcher_definition_delete", "void", [koffi.pointer("MatchingRuleDefinitionResult")]),
    matcherDefinitionGenerator: lib.func("pactffi_matcher_definition_generator", koffi.pointer("Generator"), [koffi.pointer("MatchingRuleDefinitionResult")]),
    matcherDefinitionValueType: lib.func("pactffi_matcher_definition_value_type", "int32", [koffi.pointer("MatchingRuleDefinitionResult")]),
    matchingRuleIterDelete: lib.func("pactffi_matching_rule_iter_delete", "void", [koffi.pointer("MatchingRuleIterator")]),
    matcherDefinitionIter: lib.func("pactffi_matcher_definition_iter", koffi.pointer("MatchingRuleIterator"), [koffi.pointer("MatchingRuleDefinitionResult")]),
    matchingRuleIterNext: lib.func("pactffi_matching_rule_iter_next", koffi.pointer("MatchingRuleResult"), [koffi.pointer("MatchingRuleIterator")]),
    matchingRuleId: lib.func("pactffi_matching_rule_id", "uint16", [koffi.pointer("MatchingRuleResult")]),
    matchingRuleValue: lib.func("pactffi_matching_rule_value", "string", [koffi.pointer("MatchingRuleResult")]),
    matchingRulePointer: lib.func("pactffi_matching_rule_pointer", koffi.pointer("MatchingRule"), [koffi.pointer("MatchingRuleResult")]),
    matchingRuleReferenceName: lib.func("pactffi_matching_rule_reference_name", "string", [koffi.pointer("MatchingRuleResult")]),
    validateDatetime: lib.func("pactffi_validate_datetime", "int32", ["string", "string"]),
    generatorToJson: lib.func("pactffi_generator_to_json", "string", [koffi.pointer("Generator")]),
    generatorGenerateString: lib.func("pactffi_generator_generate_string", "string", [koffi.pointer("Generator"), "string"]),
    generatorGenerateInteger: lib.func("pactffi_generator_generate_integer", "uint16", [koffi.pointer("Generator"), "string"]),
    generatorsIterDelete: lib.func("pactffi_generators_iter_delete", "void", [koffi.pointer("GeneratorCategoryIterator")]),
    generatorsIterNext: lib.func("pactffi_generators_iter_next", "string", [koffi.pointer("GeneratorCategoryIterator")]),
    generatorsIterPairDelete: lib.func("pactffi_generators_iter_pair_delete", "void", ["string"]),
    syncHttpNew: lib.func("pactffi_sync_http_new", koffi.pointer("SynchronousHttp"), []),
    syncHttpDelete: lib.func("pactffi_sync_http_delete", "void", [koffi.pointer("SynchronousHttp")]),
    syncHttpGetRequest: lib.func("pactffi_sync_http_get_request", koffi.pointer("HttpRequest"), [koffi.pointer("SynchronousHttp")]),
    syncHttpGetRequestContents: lib.func("pactffi_sync_http_get_request_contents", "string", [koffi.pointer("SynchronousHttp")]),
    syncHttpSetRequestContents: lib.func("pactffi_sync_http_set_request_contents", "void", [koffi.pointer("SynchronousHttp"), "string", "string"]),
    syncHttpGetRequestContentsLength: lib.func("pactffi_sync_http_get_request_contents_length", "size_t", [koffi.pointer("SynchronousHttp")]),
    syncHttpGetRequestContentsBin: lib.func("pactffi_sync_http_get_request_contents_bin", "uint8", [koffi.pointer("SynchronousHttp")]),
    syncHttpSetRequestContentsBin: lib.func("pactffi_sync_http_set_request_contents_bin", "void", [koffi.pointer("SynchronousHttp"), "uint8", "size_t", "string"]),
    syncHttpGetResponse: lib.func("pactffi_sync_http_get_response", koffi.pointer("HttpResponse"), [koffi.pointer("SynchronousHttp")]),
    syncHttpGetResponseContents: lib.func("pactffi_sync_http_get_response_contents", "string", [koffi.pointer("SynchronousHttp")]),
    syncHttpSetResponseContents: lib.func("pactffi_sync_http_set_response_contents", "void", [koffi.pointer("SynchronousHttp"), "string", "string"]),
    syncHttpGetResponseContentsLength: lib.func("pactffi_sync_http_get_response_contents_length", "size_t", [koffi.pointer("SynchronousHttp")]),
    syncHttpGetResponseContentsBin: lib.func("pactffi_sync_http_get_response_contents_bin", "uint8", [koffi.pointer("SynchronousHttp")]),
    syncHttpSetResponseContentsBin: lib.func("pactffi_sync_http_set_response_contents_bin", "void", [koffi.pointer("SynchronousHttp"), "uint8", "size_t", "string"]),
    syncHttpGetDescription: lib.func("pactffi_sync_http_get_description", "string", [koffi.pointer("SynchronousHttp")]),
    syncHttpSetDescription: lib.func("pactffi_sync_http_set_description", "int32", [koffi.pointer("SynchronousHttp"), "string"]),
    syncHttpGetProviderState: lib.func("pactffi_sync_http_get_provider_state", koffi.pointer("ProviderState"), [koffi.pointer("SynchronousHttp"), "uint32"]),
    syncHttpGetProviderStateIter: lib.func("pactffi_sync_http_get_provider_state_iter", koffi.pointer("ProviderStateIterator"), [koffi.pointer("SynchronousHttp")]),
    pactInteractionAsSynchronousHttp: lib.func("pactffi_pact_interaction_as_synchronous_http", koffi.pointer("SynchronousHttp"), [koffi.pointer("PactInteraction")]),
    pactInteractionAsMessage: lib.func("pactffi_pact_interaction_as_message", koffi.pointer("Message"), [koffi.pointer("PactInteraction")]),
    pactInteractionAsAsynchronousMessage: lib.func("pactffi_pact_interaction_as_asynchronous_message", koffi.pointer("AsynchronousMessage"), [koffi.pointer("PactInteraction")]),
    pactInteractionAsSynchronousMessage: lib.func("pactffi_pact_interaction_as_synchronous_message", koffi.pointer("SynchronousMessage"), [koffi.pointer("PactInteraction")]),
    pactMessageIterDelete: lib.func("pactffi_pact_message_iter_delete", "void", [koffi.pointer("PactMessageIterator")]),
    pactMessageIterNext: lib.func("pactffi_pact_message_iter_next", koffi.pointer("Message"), [koffi.pointer("PactMessageIterator")]),
    pactSyncMessageIterNext: lib.func("pactffi_pact_sync_message_iter_next", koffi.pointer("SynchronousMessage"), [koffi.pointer("PactSyncMessageIterator")]),
    pactSyncMessageIterDelete: lib.func("pactffi_pact_sync_message_iter_delete", "void", [koffi.pointer("PactSyncMessageIterator")]),
    pactSyncHttpIterNext: lib.func("pactffi_pact_sync_http_iter_next", koffi.pointer("SynchronousHttp"), [koffi.pointer("PactSyncHttpIterator")]),
    pactSyncHttpIterDelete: lib.func("pactffi_pact_sync_http_iter_delete", "void", [koffi.pointer("PactSyncHttpIterator")]),
    pactInteractionIterNext: lib.func("pactffi_pact_interaction_iter_next", koffi.pointer("PactInteraction"), [koffi.pointer("PactInteractionIterator")]),
    pactInteractionIterDelete: lib.func("pactffi_pact_interaction_iter_delete", "void", [koffi.pointer("PactInteractionIterator")]),
    matchingRuleToJson: lib.func("pactffi_matching_rule_to_json", "string", [koffi.pointer("MatchingRule")]),
    matchingRulesIterDelete: lib.func("pactffi_matching_rules_iter_delete", "void", [koffi.pointer("MatchingRuleCategoryIterator")]),
    matchingRulesIterNext: lib.func("pactffi_matching_rules_iter_next", "string", [koffi.pointer("MatchingRuleCategoryIterator")]),
    matchingRulesIterPairDelete: lib.func("pactffi_matching_rules_iter_pair_delete", "void", ["string"]),
    messageNew: lib.func("pactffi_message_new", koffi.pointer("Message"), []),
    messageNewFromJson: lib.func("pactffi_message_new_from_json", koffi.pointer("Message"), ["uint32", "string", "int32"]),
    messageNewFromBody: lib.func("pactffi_message_new_from_body", koffi.pointer("Message"), ["string", "string"]),
    messageDelete: lib.func("pactffi_message_delete", "void", [koffi.pointer("Message")]),
    messageGetContents: lib.func("pactffi_message_get_contents", "string", [koffi.pointer("Message")]),
    messageSetContents: lib.func("pactffi_message_set_contents", "void", [koffi.pointer("Message"), "string", "string"]),
    messageGetContentsLength: lib.func("pactffi_message_get_contents_length", "size_t", [koffi.pointer("Message")]),
    messageGetContentsBin: lib.func("pactffi_message_get_contents_bin", "uint8", [koffi.pointer("Message")]),
    messageSetContentsBin: lib.func("pactffi_message_set_contents_bin", "void", [koffi.pointer("Message"), "uint8", "size_t", "string"]),
    messageGetDescription: lib.func("pactffi_message_get_description", "string", [koffi.pointer("Message")]),
    messageSetDescription: lib.func("pactffi_message_set_description", "int32", [koffi.pointer("Message"), "string"]),
    messageGetProviderState: lib.func("pactffi_message_get_provider_state", koffi.pointer("ProviderState"), [koffi.pointer("Message"), "uint32"]),
    messageGetProviderStateIter: lib.func("pactffi_message_get_provider_state_iter", koffi.pointer("ProviderStateIterator"), [koffi.pointer("Message")]),
    providerStateIterNext: lib.func("pactffi_provider_state_iter_next", koffi.pointer("ProviderState"), [koffi.pointer("ProviderStateIterator")]),
    providerStateIterDelete: lib.func("pactffi_provider_state_iter_delete", "void", [koffi.pointer("ProviderStateIterator")]),
    messageFindMetadata: lib.func("pactffi_message_find_metadata", "string", [koffi.pointer("Message"), "string"]),
    messageInsertMetadata: lib.func("pactffi_message_insert_metadata", "int32", [koffi.pointer("Message"), "string", "string"]),
    messageMetadataIterNext: lib.func("pactffi_message_metadata_iter_next", "string", [koffi.pointer("MessageMetadataIterator")]),
    messageGetMetadataIter: lib.func("pactffi_message_get_metadata_iter", koffi.pointer("MessageMetadataIterator"), [koffi.pointer("Message")]),
    messageMetadataIterDelete: lib.func("pactffi_message_metadata_iter_delete", "void", [koffi.pointer("MessageMetadataIterator")]),
    messageMetadataPairDelete: lib.func("pactffi_message_metadata_pair_delete", "void", ["string"]),
    messagePactNewFromJson: lib.func("pactffi_message_pact_new_from_json", koffi.pointer("MessagePact"), ["string", "string"]),
    messagePactDelete: lib.func("pactffi_message_pact_delete", "void", [koffi.pointer("MessagePact")]),
    messagePactGetConsumer: lib.func("pactffi_message_pact_get_consumer", koffi.pointer("Consumer"), [koffi.pointer("MessagePact")]),
    messagePactGetProvider: lib.func("pactffi_message_pact_get_provider", koffi.pointer("Provider"), [koffi.pointer("MessagePact")]),
    messagePactGetMessageIter: lib.func("pactffi_message_pact_get_message_iter", koffi.pointer("MessagePactMessageIterator"), [koffi.pointer("MessagePact")]),
    messagePactMessageIterNext: lib.func("pactffi_message_pact_message_iter_next", koffi.pointer("Message"), [koffi.pointer("MessagePactMessageIterator")]),
    messagePactMessageIterDelete: lib.func("pactffi_message_pact_message_iter_delete", "void", [koffi.pointer("MessagePactMessageIterator")]),
    messagePactFindMetadata: lib.func("pactffi_message_pact_find_metadata", "string", [koffi.pointer("MessagePact"), "string", "string"]),
    messagePactGetMetadataIter: lib.func("pactffi_message_pact_get_metadata_iter", koffi.pointer("MessagePactMetadataIterator"), [koffi.pointer("MessagePact")]),
    messagePactMetadataIterNext: lib.func("pactffi_message_pact_metadata_iter_next", "string", [koffi.pointer("MessagePactMetadataIterator")]),
    messagePactMetadataIterDelete: lib.func("pactffi_message_pact_metadata_iter_delete", "void", [koffi.pointer("MessagePactMetadataIterator")]),
    messagePactMetadataTripleDelete: lib.func("pactffi_message_pact_metadata_triple_delete", "void", ["string"]),
    providerGetName: lib.func("pactffi_provider_get_name", "string", [koffi.pointer("Provider")]),
    pactGetProvider: lib.func("pactffi_pact_get_provider", koffi.pointer("Provider"), [koffi.pointer("Pact")]),
    pactProviderDelete: lib.func("pactffi_pact_provider_delete", "void", [koffi.pointer("Provider")]),
    providerStateGetName: lib.func("pactffi_provider_state_get_name", "string", [koffi.pointer("ProviderState")]),
    providerStateGetParamIter: lib.func("pactffi_provider_state_get_param_iter", koffi.pointer("ProviderStateParamIterator"), [koffi.pointer("ProviderState")]),
    providerStateParamIterNext: lib.func("pactffi_provider_state_param_iter_next", "string", [koffi.pointer("ProviderStateParamIterator")]),
    providerStateDelete: lib.func("pactffi_provider_state_delete", "void", [koffi.pointer("ProviderState")]),
    providerStateParamIterDelete: lib.func("pactffi_provider_state_param_iter_delete", "void", [koffi.pointer("ProviderStateParamIterator")]),
    providerStateParamPairDelete: lib.func("pactffi_provider_state_param_pair_delete", "void", ["string"]),
    syncMessageNew: lib.func("pactffi_sync_message_new", koffi.pointer("SynchronousMessage"), []),
    syncMessageDelete: lib.func("pactffi_sync_message_delete", "void", [koffi.pointer("SynchronousMessage")]),
    syncMessageGetRequestContentsStr: lib.func("pactffi_sync_message_get_request_contents_str", "string", [koffi.pointer("SynchronousMessage")]),
    syncMessageSetRequestContentsStr: lib.func("pactffi_sync_message_set_request_contents_str", "void", [koffi.pointer("SynchronousMessage"), "string", "string"]),
    syncMessageGetRequestContentsLength: lib.func("pactffi_sync_message_get_request_contents_length", "size_t", [koffi.pointer("SynchronousMessage")]),
    syncMessageGetRequestContentsBin: lib.func("pactffi_sync_message_get_request_contents_bin", "uint8", [koffi.pointer("SynchronousMessage")]),
    syncMessageSetRequestContentsBin: lib.func("pactffi_sync_message_set_request_contents_bin", "void", [koffi.pointer("SynchronousMessage"), "uint8", "size_t", "string"]),
    syncMessageGetRequestContents: lib.func("pactffi_sync_message_get_request_contents", koffi.pointer("MessageContents"), [koffi.pointer("SynchronousMessage")]),
    syncMessageGetNumberResponses: lib.func("pactffi_sync_message_get_number_responses", "size_t", [koffi.pointer("SynchronousMessage")]),
    syncMessageGetResponseContentsStr: lib.func("pactffi_sync_message_get_response_contents_str", "string", [koffi.pointer("SynchronousMessage"), "size_t"]),
    syncMessageSetResponseContentsStr: lib.func("pactffi_sync_message_set_response_contents_str", "void", [koffi.pointer("SynchronousMessage"), "size_t", "string", "string"]),
    syncMessageGetResponseContentsLength: lib.func("pactffi_sync_message_get_response_contents_length", "size_t", [koffi.pointer("SynchronousMessage"), "size_t"]),
    syncMessageGetResponseContentsBin: lib.func("pactffi_sync_message_get_response_contents_bin", "uint8", [koffi.pointer("SynchronousMessage"), "size_t"]),
    syncMessageSetResponseContentsBin: lib.func("pactffi_sync_message_set_response_contents_bin", "void", [koffi.pointer("SynchronousMessage"), "size_t", "uint8", "size_t", "string"]),
    syncMessageGetResponseContents: lib.func("pactffi_sync_message_get_response_contents", koffi.pointer("MessageContents"), [koffi.pointer("SynchronousMessage"), "size_t"]),
    syncMessageGetDescription: lib.func("pactffi_sync_message_get_description", "string", [koffi.pointer("SynchronousMessage")]),
    syncMessageSetDescription: lib.func("pactffi_sync_message_set_description", "int32", [koffi.pointer("SynchronousMessage"), "string"]),
    syncMessageGetProviderState: lib.func("pactffi_sync_message_get_provider_state", koffi.pointer("ProviderState"), [koffi.pointer("SynchronousMessage"), "uint32"]),
    syncMessageGetProviderStateIter: lib.func("pactffi_sync_message_get_provider_state_iter", koffi.pointer("ProviderStateIterator"), [koffi.pointer("SynchronousMessage")]),
    stringDelete: lib.func("pactffi_string_delete", "void", ["string"]),
    createMockServer: lib.func('int32_t pactffi_create_mock_server(const char *pact_str,const char *addr_str,bool tls)'),
    getTlsCaCertificate: lib.func("pactffi_get_tls_ca_certificate", "string", []),
    createMockServerForPact: lib.func("pactffi_create_mock_server_for_pact", "int32", ["uint16", "string", "uint8"]),
    createMockServerForTransport: lib.func("pactffi_create_mock_server_for_transport", "int32", ["uint16", "string", "uint16", "string", "string"]),
    mockServerMatched: lib.func("pactffi_mock_server_matched", "uint8", ["int32"]),
    mockServerMismatches: lib.func("pactffi_mock_server_mismatches", "string", ["int32"]),
    cleanupMockServer: lib.func("pactffi_cleanup_mock_server", "uint8", ["int32"]),
    writePactFile: lib.func("pactffi_write_pact_file", "int32", ["int32", "string", "uint8"]),
    mockServerLogs: lib.func("pactffi_mock_server_logs", "string", ["int32"]),
    generateDatetimeString: lib.func("pactffi_generate_datetime_string", "string", ["string"]),
    checkRegex: lib.func("pactffi_check_regex", "uint8", ["string", "string"]),
    generateRegexValue: lib.func("pactffi_generate_regex_value", "string", ["string"]),
    freeString: lib.func("pactffi_free_string", "void", ["string"]),
    newPact: lib.func("pactffi_new_pact", "uint16", ["string", "string"]),
    newInteraction: lib.func("pactffi_new_interaction", "uint32", ["uint16", "string"]),
    newMessageInteraction: lib.func("pactffi_new_message_interaction", "uint32", ["uint16", "string"]),
    newSyncMessageInteraction: lib.func("pactffi_new_sync_message_interaction", "uint32", ["uint16", "string"]),
    uponReceiving: lib.func("pactffi_upon_receiving", "uint8", ["uint32", "string"]),
    given: lib.func("pactffi_given", "uint8", ["uint32", "string"]),
    interactionTestName: lib.func("pactffi_interaction_test_name", "uint32", ["uint32", "string"]),
    givenWithParam: lib.func("pactffi_given_with_param", "uint8", ["uint32", "string", "string", "string"]),
    withRequest: lib.func("pactffi_with_request", "uint8", ["uint32", "string", "string"]),
    withQueryParameter: lib.func("pactffi_with_query_parameter", "uint8", ["uint32", "string", "size_t", "string"]),
    withQueryParameterV2: lib.func("pactffi_with_query_parameter_v2", "uint8", ["uint32", "string", "size_t", "string"]),
    withSpecification: lib.func("pactffi_with_specification", "uint8", ["uint16", "int32"]),
    withPactMetadata: lib.func("pactffi_with_pact_metadata", "uint8", ["uint16", "string", "string", "string"]),
    withHeader: lib.func("pactffi_with_header", "uint8", ["uint32", "int32", "string", "size_t", "string"]),
    withHeaderV2: lib.func("pactffi_with_header_v2", "uint8", ["uint32", "int32", "string", "size_t", "string"]),
    responseStatus: lib.func("pactffi_response_status", "uint8", ["uint32", "uint16"]),
    withBody: lib.func("pactffi_with_body", "uint8", ["uint32", "int32", "string", "string"]),
    withBinaryFile: lib.func("pactffi_with_binary_file", "uint8", ["uint32", "int32", "string", "uint8", "size_t"]),
    withMultipartFile: lib.func("pactffi_with_multipart_file", "string", ["uint32", "int32", "string", "string", "string"]),
    pactHandleGetMessageIter: lib.func("pactffi_pact_handle_get_message_iter", koffi.pointer("PactMessageIterator"), ["uint16"]),
    pactHandleGetSyncMessageIter: lib.func("pactffi_pact_handle_get_sync_message_iter", koffi.pointer("PactSyncMessageIterator"), ["uint16"]),
    pactHandleGetSyncHttpIter: lib.func("pactffi_pact_handle_get_sync_http_iter", koffi.pointer("PactSyncHttpIterator"), ["uint16"]),
    newMessagePact: lib.func("pactffi_new_message_pact", "uint16", ["string", "string"]),
    newMessage: lib.func("pactffi_new_message", "uint32", ["uint16", "string"]),
    messageExpectsToReceive: lib.func("pactffi_message_expects_to_receive", "void", ["uint32", "string"]),
    messageGiven: lib.func("pactffi_message_given", "void", ["uint32", "string"]),
    messageGivenWithParam: lib.func("pactffi_message_given_with_param", "void", ["uint32", "string", "string", "string"]),
    messageWithContents: lib.func("pactffi_message_with_contents", "void", ["uint32", "string", "uint8", "size_t"]),
    messageWithMetadata: lib.func("pactffi_message_with_metadata", "void", ["uint32", "string", "string"]),
    messageReify: lib.func("pactffi_message_reify", "string", ["uint32"]),
    writeMessagePactFile: lib.func("pactffi_write_message_pact_file", "int32", ["uint16", "string", "uint8"]),
    withMessagePactMetadata: lib.func("pactffi_with_message_pact_metadata", "void", ["uint16", "string", "string", "string"]),
    pactHandleWriteFile: lib.func("pactffi_pact_handle_write_file", "int32", ["uint16", "string", "uint8"]),
    newAsyncMessage: lib.func("pactffi_new_async_message", "uint32", ["uint16", "string"]),
    freePactHandle: lib.func("pactffi_free_pact_handle", "uint32", ["uint16"]),
    freeMessagePactHandle: lib.func("pactffi_free_message_pact_handle", "uint32", ["uint16"]),
    verify: lib.func("pactffi_verify", "int32", ["string"]),
    verifierNew: lib.func("pactffi_verifier_new", koffi.pointer("VerifierHandle"), []),
    verifierNewForApplication: lib.func("pactffi_verifier_new_for_application", koffi.pointer("VerifierHandle"), ["string", "string"]),
    verifierShutdown: lib.func("pactffi_verifier_shutdown", "void", [koffi.pointer("VerifierHandle")]),
    verifierSetProviderInfo: lib.func("pactffi_verifier_set_provider_info", "void", [koffi.pointer("VerifierHandle"), "string", "string", "string", "uint16", "string"]),
    verifierAddProviderTransport: lib.func("pactffi_verifier_add_provider_transport", "void", [koffi.pointer("VerifierHandle"), "string", "uint16", "string", "string"]),
    verifierSetFilterInfo: lib.func("pactffi_verifier_set_filter_info", "void", [koffi.pointer("VerifierHandle"), "string", "string", "uint8"]),
    verifierSetProviderState: lib.func("pactffi_verifier_set_provider_state", "void", [koffi.pointer("VerifierHandle"), "string", "uint8", "uint8"]),
    verifierSetVerificationOptions: lib.func("pactffi_verifier_set_verification_options", "int32", [koffi.pointer("VerifierHandle"), "uint8", "uint64"]),
    verifierSetColouredOutput: lib.func("pactffi_verifier_set_coloured_output", "int32", [koffi.pointer("VerifierHandle"), "uint8"]),
    verifierSetNoPactsIsError: lib.func("pactffi_verifier_set_no_pacts_is_error", "int32", [koffi.pointer("VerifierHandle"), "uint8"]),
    verifierSetPublishOptions: lib.func("pactffi_verifier_set_publish_options", "int32", [koffi.pointer("VerifierHandle"), "string", "string", "string", "uint16", "string"]),
    verifierSetConsumerFilters: lib.func("pactffi_verifier_set_consumer_filters", "void", [koffi.pointer("VerifierHandle"), "string", "uint16"]),
    verifierAddCustomHeader: lib.func("pactffi_verifier_add_custom_header", "void", [koffi.pointer("VerifierHandle"), "string", "string"]),
    verifierAddFileSource: lib.func("pactffi_verifier_add_file_source", "void", [koffi.pointer("VerifierHandle"), "string"]),
    verifierAddDirectorySource: lib.func("pactffi_verifier_add_directory_source", "void", [koffi.pointer("VerifierHandle"), "string"]),
    verifierUrlSource: lib.func("pactffi_verifier_url_source", "void", [koffi.pointer("VerifierHandle"), "string", "string", "string", "string"]),
    verifierBrokerSource: lib.func("pactffi_verifier_broker_source", "void", [koffi.pointer("VerifierHandle"), "string", "string", "string", "string"]),
    verifierBrokerSourceWithSelectors: lib.func("pactffi_verifier_broker_source_with_selectors", "void", [koffi.pointer("VerifierHandle"), "string", "string", "string", "string", "uint8", "string", "string", "uint16", "string", "string", "uint16", "string", "uint16"]),
    verifierExecute: lib.func("pactffi_verifier_execute", "int32", [koffi.pointer("VerifierHandle")]),
    verifierCliArgs: lib.func("pactffi_verifier_cli_args", "string", []),
    verifierLogs: lib.func("pactffi_verifier_logs", "string", [koffi.pointer("VerifierHandle")]),
    verifierLogsForProvider: lib.func("pactffi_verifier_logs_for_provider", "string", ["string"]),
    verifierOutput: lib.func("pactffi_verifier_output", "string", [koffi.pointer("VerifierHandle"), "uint8"]),
    verifierJson: lib.func("pactffi_verifier_json", "string", [koffi.pointer("VerifierHandle")]),
    usingPlugin: lib.func("pactffi_using_plugin", "uint32", ["uint16", "string", "string"]),
    cleanupPlugins: lib.func("pactffi_cleanup_plugins", "void", ["uint16"]),
    interactionContents: lib.func("pactffi_interaction_contents", "uint32", ["uint32", "int32", "string", "string"]),
    matchesStringValue: lib.func("pactffi_matches_string_value", "string", [koffi.pointer("MatchingRule"), "string", "string", "uint8"]),
    matchesU64Value: lib.func("pactffi_matches_u64_value", "string", [koffi.pointer("MatchingRule"), "uint64", "uint64", "uint8"]),
    matchesI64Value: lib.func("pactffi_matches_i64_value", "string", [koffi.pointer("MatchingRule"), "int64", "int64", "uint8"]),
    matchesF64Value: lib.func("pactffi_matches_f64_value", "string", [koffi.pointer("MatchingRule"), "double", "double", "uint8"]),
    matchesBoolValue: lib.func("pactffi_matches_bool_value", "string", [koffi.pointer("MatchingRule"), "uint8", "uint8", "uint8"]),
    matchesBinaryValue: lib.func("pactffi_matches_binary_value", "string", [koffi.pointer("MatchingRule"), "uint8", "uint64", "uint8", "uint64", "uint8"]),
    matchesJsonValue: lib.func("pactffi_matches_json_value", "string", [koffi.pointer("MatchingRule"), "string", "string", "uint8"])
        
    }
  } 
console.log(`Hello Ffi!\n ${PactKoffi().version()}`);  