import path from 'path';
console.log({ arch: process.arch, platform: process.platform });
const libPath = path.join(
__dirname,
'ffi',
`${process.platform}-${process.arch}`,
`${process.platform !== 'win32' ? 'lib' : ''}pact_ffi.${
  process.platform === 'win32'
    ? 'dll'
    : process.platform === 'darwin'
    ? 'dylib'
    : 'so'
}`);
console.log('libPath', libPath);
import koffi from 'koffi';
const lib = koffi.load(libPath);
export const PactFfiLib = () => {
  return  {
  malloc: lib.func("malloc", "string", ["size_t"]),
  calloc: lib.func("calloc", "string", ["size_t", "size_t"]),
  realloc: lib.func("realloc", "string", ["string", "size_t"]),
  free: lib.func("free", "void", ["string"]),
  posix_memalign: lib.func("posix_memalign", "int32", ["string", "size_t", "size_t"]),
  abort: lib.func("abort", "void", []),
  getenv: lib.func("getenv", "string", ["string"]),
  realpath: lib.func("realpath", "string", ["string", "string"]),
  pactffi_version: lib.func("pactffi_version", "string", []),
  pactffi_init: lib.func("pactffi_init", "void", ["string"]),
  pactffi_init_with_log_level: lib.func("pactffi_init_with_log_level", "void", ["string"]),
  pactffi_enable_ansi_support: lib.func("pactffi_enable_ansi_support", "void", []),
  pactffi_log_message: lib.func("pactffi_log_message", "void", ["string", "string", "string"]),
  pactffi_match_message: lib.func("pactffi_match_message", "string", ["string", "string"]),
  pactffi_mismatches_get_iter: lib.func("pactffi_mismatches_get_iter", "string", ["string"]),
  pactffi_mismatches_delete: lib.func("pactffi_mismatches_delete", "void", ["string"]),
  pactffi_mismatches_iter_next: lib.func("pactffi_mismatches_iter_next", "string", ["string"]),
  pactffi_mismatches_iter_delete: lib.func("pactffi_mismatches_iter_delete", "void", ["string"]),
  pactffi_mismatch_to_json: lib.func("pactffi_mismatch_to_json", "string", ["string"]),
  pactffi_mismatch_type: lib.func("pactffi_mismatch_type", "string", ["string"]),
  pactffi_mismatch_summary: lib.func("pactffi_mismatch_summary", "string", ["string"]),
  pactffi_mismatch_description: lib.func("pactffi_mismatch_description", "string", ["string"]),
  pactffi_mismatch_ansi_description: lib.func("pactffi_mismatch_ansi_description", "string", ["string"]),
  pactffi_get_error_message: lib.func("pactffi_get_error_message", "int32", ["string", "int32"]),
  pactffi_log_to_stdout: lib.func("pactffi_log_to_stdout", "int32", ["int32"]),
  pactffi_log_to_stderr: lib.func("pactffi_log_to_stderr", "int32", ["int32"]),
  pactffi_log_to_file: lib.func("pactffi_log_to_file", "int32", ["string", "int32"]),
  pactffi_log_to_buffer: lib.func("pactffi_log_to_buffer", "int32", ["int32"]),
  pactffi_logger_init: lib.func("pactffi_logger_init", "void", []),
  pactffi_logger_attach_sink: lib.func("pactffi_logger_attach_sink", "int32", ["string", "int32"]),
  pactffi_logger_apply: lib.func("pactffi_logger_apply", "int32", []),
  pactffi_fetch_log_buffer: lib.func("pactffi_fetch_log_buffer", "string", ["string"]),
  pactffi_parse_pact_json: lib.func("pactffi_parse_pact_json", "string", ["string"]),
  pactffi_pact_model_delete: lib.func("pactffi_pact_model_delete", "void", ["string"]),
  pactffi_pact_model_interaction_iterator: lib.func("pactffi_pact_model_interaction_iterator", "string", ["string"]),
  pactffi_pact_spec_version: lib.func("pactffi_pact_spec_version", "int32", ["string"]),
  pactffi_pact_interaction_delete: lib.func("pactffi_pact_interaction_delete", "void", ["string"]),
  pactffi_async_message_new: lib.func("pactffi_async_message_new", "string", []),
  pactffi_async_message_delete: lib.func("pactffi_async_message_delete", "void", ["string"]),
  pactffi_async_message_get_contents: lib.func("pactffi_async_message_get_contents", "string", ["string"]),
  pactffi_async_message_get_contents_str: lib.func("pactffi_async_message_get_contents_str", "string", ["string"]),
  pactffi_async_message_set_contents_str: lib.func("pactffi_async_message_set_contents_str", "void", ["string", "string", "string"]),
  pactffi_async_message_get_contents_length: lib.func("pactffi_async_message_get_contents_length", "size_t", ["string"]),
  pactffi_async_message_get_contents_bin: lib.func("pactffi_async_message_get_contents_bin", "string", ["string"]),
  pactffi_async_message_set_contents_bin: lib.func("pactffi_async_message_set_contents_bin", "void", ["string", "string", "size_t", "string"]),
  pactffi_async_message_get_description: lib.func("pactffi_async_message_get_description", "string", ["string"]),
  pactffi_async_message_set_description: lib.func("pactffi_async_message_set_description", "int32", ["string", "string"]),
  pactffi_async_message_get_provider_state: lib.func("pactffi_async_message_get_provider_state", "string", ["string", "uint32"]),
  pactffi_async_message_get_provider_state_iter: lib.func("pactffi_async_message_get_provider_state_iter", "string", ["string"]),
  pactffi_consumer_get_name: lib.func("pactffi_consumer_get_name", "string", ["string"]),
  pactffi_pact_get_consumer: lib.func("pactffi_pact_get_consumer", "string", ["string"]),
  pactffi_pact_consumer_delete: lib.func("pactffi_pact_consumer_delete", "void", ["string"]),
  pactffi_message_contents_get_contents_str: lib.func("pactffi_message_contents_get_contents_str", "string", ["string"]),
  pactffi_message_contents_set_contents_str: lib.func("pactffi_message_contents_set_contents_str", "void", ["string", "string", "string"]),
  pactffi_message_contents_get_contents_length: lib.func("pactffi_message_contents_get_contents_length", "size_t", ["string"]),
  pactffi_message_contents_get_contents_bin: lib.func("pactffi_message_contents_get_contents_bin", "string", ["string"]),
  pactffi_message_contents_set_contents_bin: lib.func("pactffi_message_contents_set_contents_bin", "void", ["string", "string", "size_t", "string"]),
  pactffi_message_contents_get_metadata_iter: lib.func("pactffi_message_contents_get_metadata_iter", "string", ["string"]),
  pactffi_message_contents_get_matching_rule_iter: lib.func("pactffi_message_contents_get_matching_rule_iter", "string", ["string", "int32"]),
  pactffi_request_contents_get_matching_rule_iter: lib.func("pactffi_request_contents_get_matching_rule_iter", "string", ["string", "int32"]),
  pactffi_response_contents_get_matching_rule_iter: lib.func("pactffi_response_contents_get_matching_rule_iter", "string", ["string", "int32"]),
  pactffi_message_contents_get_generators_iter: lib.func("pactffi_message_contents_get_generators_iter", "string", ["string", "int32"]),
  pactffi_request_contents_get_generators_iter: lib.func("pactffi_request_contents_get_generators_iter", "string", ["string", "int32"]),
  pactffi_response_contents_get_generators_iter: lib.func("pactffi_response_contents_get_generators_iter", "string", ["string", "int32"]),
  pactffi_parse_matcher_definition: lib.func("pactffi_parse_matcher_definition", "string", ["string"]),
  pactffi_matcher_definition_error: lib.func("pactffi_matcher_definition_error", "string", ["string"]),
  pactffi_matcher_definition_value: lib.func("pactffi_matcher_definition_value", "string", ["string"]),
  pactffi_matcher_definition_delete: lib.func("pactffi_matcher_definition_delete", "void", ["string"]),
  pactffi_matcher_definition_generator: lib.func("pactffi_matcher_definition_generator", "string", ["string"]),
  pactffi_matcher_definition_value_type: lib.func("pactffi_matcher_definition_value_type", "int32", ["string"]),
  pactffi_matching_rule_iter_delete: lib.func("pactffi_matching_rule_iter_delete", "void", ["string"]),
  pactffi_matcher_definition_iter: lib.func("pactffi_matcher_definition_iter", "string", ["string"]),
  pactffi_matching_rule_iter_next: lib.func("pactffi_matching_rule_iter_next", "string", ["string"]),
  pactffi_matching_rule_id: lib.func("pactffi_matching_rule_id", "uint16", ["string"]),
  pactffi_matching_rule_value: lib.func("pactffi_matching_rule_value", "string", ["string"]),
  pactffi_matching_rule_pointer: lib.func("pactffi_matching_rule_pointer", "string", ["string"]),
  pactffi_matching_rule_reference_name: lib.func("pactffi_matching_rule_reference_name", "string", ["string"]),
  pactffi_validate_datetime: lib.func("pactffi_validate_datetime", "int32", ["string", "string"]),
  pactffi_generator_to_json: lib.func("pactffi_generator_to_json", "string", ["string"]),
  pactffi_generator_generate_string: lib.func("pactffi_generator_generate_string", "string", ["string", "string"]),
  pactffi_generator_generate_integer: lib.func("pactffi_generator_generate_integer", "uint16", ["string", "string"]),
  pactffi_generators_iter_delete: lib.func("pactffi_generators_iter_delete", "void", ["string"]),
  pactffi_generators_iter_next: lib.func("pactffi_generators_iter_next", "string", ["string"]),
  pactffi_generators_iter_pair_delete: lib.func("pactffi_generators_iter_pair_delete", "void", ["string"]),
  pactffi_sync_http_new: lib.func("pactffi_sync_http_new", "string", []),
  pactffi_sync_http_delete: lib.func("pactffi_sync_http_delete", "void", ["string"]),
  pactffi_sync_http_get_request: lib.func("pactffi_sync_http_get_request", "string", ["string"]),
  pactffi_sync_http_get_request_contents: lib.func("pactffi_sync_http_get_request_contents", "string", ["string"]),
  pactffi_sync_http_set_request_contents: lib.func("pactffi_sync_http_set_request_contents", "void", ["string", "string", "string"]),
  pactffi_sync_http_get_request_contents_length: lib.func("pactffi_sync_http_get_request_contents_length", "size_t", ["string"]),
  pactffi_sync_http_get_request_contents_bin: lib.func("pactffi_sync_http_get_request_contents_bin", "string", ["string"]),
  pactffi_sync_http_set_request_contents_bin: lib.func("pactffi_sync_http_set_request_contents_bin", "void", ["string", "string", "size_t", "string"]),
  pactffi_sync_http_get_response: lib.func("pactffi_sync_http_get_response", "string", ["string"]),
  pactffi_sync_http_get_response_contents: lib.func("pactffi_sync_http_get_response_contents", "string", ["string"]),
  pactffi_sync_http_set_response_contents: lib.func("pactffi_sync_http_set_response_contents", "void", ["string", "string", "string"]),
  pactffi_sync_http_get_response_contents_length: lib.func("pactffi_sync_http_get_response_contents_length", "size_t", ["string"]),
  pactffi_sync_http_get_response_contents_bin: lib.func("pactffi_sync_http_get_response_contents_bin", "string", ["string"]),
  pactffi_sync_http_set_response_contents_bin: lib.func("pactffi_sync_http_set_response_contents_bin", "void", ["string", "string", "size_t", "string"]),
  pactffi_sync_http_get_description: lib.func("pactffi_sync_http_get_description", "string", ["string"]),
  pactffi_sync_http_set_description: lib.func("pactffi_sync_http_set_description", "int32", ["string", "string"]),
  pactffi_sync_http_get_provider_state: lib.func("pactffi_sync_http_get_provider_state", "string", ["string", "uint32"]),
  pactffi_sync_http_get_provider_state_iter: lib.func("pactffi_sync_http_get_provider_state_iter", "string", ["string"]),
  pactffi_pact_interaction_as_synchronous_http: lib.func("pactffi_pact_interaction_as_synchronous_http", "string", ["string"]),
  pactffi_pact_interaction_as_message: lib.func("pactffi_pact_interaction_as_message", "string", ["string"]),
  pactffi_pact_interaction_as_asynchronous_message: lib.func("pactffi_pact_interaction_as_asynchronous_message", "string", ["string"]),
  pactffi_pact_interaction_as_synchronous_message: lib.func("pactffi_pact_interaction_as_synchronous_message", "string", ["string"]),
  pactffi_pact_message_iter_delete: lib.func("pactffi_pact_message_iter_delete", "void", ["string"]),
  pactffi_pact_message_iter_next: lib.func("pactffi_pact_message_iter_next", "string", ["string"]),
  pactffi_pact_sync_message_iter_next: lib.func("pactffi_pact_sync_message_iter_next", "string", ["string"]),
  pactffi_pact_sync_message_iter_delete: lib.func("pactffi_pact_sync_message_iter_delete", "void", ["string"]),
  pactffi_pact_sync_http_iter_next: lib.func("pactffi_pact_sync_http_iter_next", "string", ["string"]),
  pactffi_pact_sync_http_iter_delete: lib.func("pactffi_pact_sync_http_iter_delete", "void", ["string"]),
  pactffi_pact_interaction_iter_next: lib.func("pactffi_pact_interaction_iter_next", "string", ["string"]),
  pactffi_pact_interaction_iter_delete: lib.func("pactffi_pact_interaction_iter_delete", "void", ["string"]),
  pactffi_matching_rule_to_json: lib.func("pactffi_matching_rule_to_json", "string", ["string"]),
  pactffi_matching_rules_iter_delete: lib.func("pactffi_matching_rules_iter_delete", "void", ["string"]),
  pactffi_matching_rules_iter_next: lib.func("pactffi_matching_rules_iter_next", "string", ["string"]),
  pactffi_matching_rules_iter_pair_delete: lib.func("pactffi_matching_rules_iter_pair_delete", "void", ["string"]),
  pactffi_message_new: lib.func("pactffi_message_new", "string", []),
  pactffi_message_new_from_json: lib.func("pactffi_message_new_from_json", "string", ["uint32", "string", "int32"]),
  pactffi_message_new_from_body: lib.func("pactffi_message_new_from_body", "string", ["string", "string"]),
  pactffi_message_delete: lib.func("pactffi_message_delete", "void", ["string"]),
  pactffi_message_get_contents: lib.func("pactffi_message_get_contents", "string", ["string"]),
  pactffi_message_set_contents: lib.func("pactffi_message_set_contents", "void", ["string", "string", "string"]),
  pactffi_message_get_contents_length: lib.func("pactffi_message_get_contents_length", "size_t", ["string"]),
  pactffi_message_get_contents_bin: lib.func("pactffi_message_get_contents_bin", "string", ["string"]),
  pactffi_message_set_contents_bin: lib.func("pactffi_message_set_contents_bin", "void", ["string", "string", "size_t", "string"]),
  pactffi_message_get_description: lib.func("pactffi_message_get_description", "string", ["string"]),
  pactffi_message_set_description: lib.func("pactffi_message_set_description", "int32", ["string", "string"]),
  pactffi_message_get_provider_state: lib.func("pactffi_message_get_provider_state", "string", ["string", "uint32"]),
  pactffi_message_get_provider_state_iter: lib.func("pactffi_message_get_provider_state_iter", "string", ["string"]),
  pactffi_provider_state_iter_next: lib.func("pactffi_provider_state_iter_next", "string", ["string"]),
  pactffi_provider_state_iter_delete: lib.func("pactffi_provider_state_iter_delete", "void", ["string"]),
  pactffi_message_find_metadata: lib.func("pactffi_message_find_metadata", "string", ["string", "string"]),
  pactffi_message_insert_metadata: lib.func("pactffi_message_insert_metadata", "int32", ["string", "string", "string"]),
  pactffi_message_metadata_iter_next: lib.func("pactffi_message_metadata_iter_next", "string", ["string"]),
  pactffi_message_get_metadata_iter: lib.func("pactffi_message_get_metadata_iter", "string", ["string"]),
  pactffi_message_metadata_iter_delete: lib.func("pactffi_message_metadata_iter_delete", "void", ["string"]),
  pactffi_message_metadata_pair_delete: lib.func("pactffi_message_metadata_pair_delete", "void", ["string"]),
  pactffi_message_pact_new_from_json: lib.func("pactffi_message_pact_new_from_json", "string", ["string", "string"]),
  pactffi_message_pact_delete: lib.func("pactffi_message_pact_delete", "void", ["string"]),
  pactffi_message_pact_get_consumer: lib.func("pactffi_message_pact_get_consumer", "string", ["string"]),
  pactffi_message_pact_get_provider: lib.func("pactffi_message_pact_get_provider", "string", ["string"]),
  pactffi_message_pact_get_message_iter: lib.func("pactffi_message_pact_get_message_iter", "string", ["string"]),
  pactffi_message_pact_message_iter_next: lib.func("pactffi_message_pact_message_iter_next", "string", ["string"]),
  pactffi_message_pact_message_iter_delete: lib.func("pactffi_message_pact_message_iter_delete", "void", ["string"]),
  pactffi_message_pact_find_metadata: lib.func("pactffi_message_pact_find_metadata", "string", ["string", "string", "string"]),
  pactffi_message_pact_get_metadata_iter: lib.func("pactffi_message_pact_get_metadata_iter", "string", ["string"]),
  pactffi_message_pact_metadata_iter_next: lib.func("pactffi_message_pact_metadata_iter_next", "string", ["string"]),
  pactffi_message_pact_metadata_iter_delete: lib.func("pactffi_message_pact_metadata_iter_delete", "void", ["string"]),
  pactffi_message_pact_metadata_triple_delete: lib.func("pactffi_message_pact_metadata_triple_delete", "void", ["string"]),
  pactffi_provider_get_name: lib.func("pactffi_provider_get_name", "string", ["string"]),
  pactffi_pact_get_provider: lib.func("pactffi_pact_get_provider", "string", ["string"]),
  pactffi_pact_provider_delete: lib.func("pactffi_pact_provider_delete", "void", ["string"]),
  pactffi_provider_state_get_name: lib.func("pactffi_provider_state_get_name", "string", ["string"]),
  pactffi_provider_state_get_param_iter: lib.func("pactffi_provider_state_get_param_iter", "string", ["string"]),
  pactffi_provider_state_param_iter_next: lib.func("pactffi_provider_state_param_iter_next", "string", ["string"]),
  pactffi_provider_state_delete: lib.func("pactffi_provider_state_delete", "void", ["string"]),
  pactffi_provider_state_param_iter_delete: lib.func("pactffi_provider_state_param_iter_delete", "void", ["string"]),
  pactffi_provider_state_param_pair_delete: lib.func("pactffi_provider_state_param_pair_delete", "void", ["string"]),
  pactffi_sync_message_new: lib.func("pactffi_sync_message_new", "string", []),
  pactffi_sync_message_delete: lib.func("pactffi_sync_message_delete", "void", ["string"]),
  pactffi_sync_message_get_request_contents_str: lib.func("pactffi_sync_message_get_request_contents_str", "string", ["string"]),
  pactffi_sync_message_set_request_contents_str: lib.func("pactffi_sync_message_set_request_contents_str", "void", ["string", "string", "string"]),
  pactffi_sync_message_get_request_contents_length: lib.func("pactffi_sync_message_get_request_contents_length", "size_t", ["string"]),
  pactffi_sync_message_get_request_contents_bin: lib.func("pactffi_sync_message_get_request_contents_bin", "string", ["string"]),
  pactffi_sync_message_set_request_contents_bin: lib.func("pactffi_sync_message_set_request_contents_bin", "void", ["string", "string", "size_t", "string"]),
  pactffi_sync_message_get_request_contents: lib.func("pactffi_sync_message_get_request_contents", "string", ["string"]),
  pactffi_sync_message_get_number_responses: lib.func("pactffi_sync_message_get_number_responses", "size_t", ["string"]),
  pactffi_sync_message_get_response_contents_str: lib.func("pactffi_sync_message_get_response_contents_str", "string", ["string", "size_t"]),
  pactffi_sync_message_set_response_contents_str: lib.func("pactffi_sync_message_set_response_contents_str", "void", ["string", "size_t", "string", "string"]),
  pactffi_sync_message_get_response_contents_length: lib.func("pactffi_sync_message_get_response_contents_length", "size_t", ["string", "size_t"]),
  pactffi_sync_message_get_response_contents_bin: lib.func("pactffi_sync_message_get_response_contents_bin", "string", ["string", "size_t"]),
  pactffi_sync_message_set_response_contents_bin: lib.func("pactffi_sync_message_set_response_contents_bin", "void", ["string", "size_t", "string", "size_t", "string"]),
  pactffi_sync_message_get_response_contents: lib.func("pactffi_sync_message_get_response_contents", "string", ["string", "size_t"]),
  pactffi_sync_message_get_description: lib.func("pactffi_sync_message_get_description", "string", ["string"]),
  pactffi_sync_message_set_description: lib.func("pactffi_sync_message_set_description", "int32", ["string", "string"]),
  pactffi_sync_message_get_provider_state: lib.func("pactffi_sync_message_get_provider_state", "string", ["string", "uint32"]),
  pactffi_sync_message_get_provider_state_iter: lib.func("pactffi_sync_message_get_provider_state_iter", "string", ["string"]),
  pactffi_string_delete: lib.func("pactffi_string_delete", "void", ["string"]),
  pactffi_create_mock_server: lib.func("pactffi_create_mock_server", "int32", ["string", "string", "uint8"]),
  pactffi_get_tls_ca_certificate: lib.func("pactffi_get_tls_ca_certificate", "string", []),
  pactffi_create_mock_server_for_pact: lib.func("pactffi_create_mock_server_for_pact", "int32", ["uint16", "string", "uint8"]),
  pactffi_create_mock_server_for_transport: lib.func("pactffi_create_mock_server_for_transport", "int32", ["uint16", "string", "uint16", "string", "string"]),
  pactffi_mock_server_matched: lib.func("pactffi_mock_server_matched", "uint8", ["int32"]),
  pactffi_mock_server_mismatches: lib.func("pactffi_mock_server_mismatches", "string", ["int32"]),
  pactffi_cleanup_mock_server: lib.func("pactffi_cleanup_mock_server", "uint8", ["int32"]),
  pactffi_write_pact_file: lib.func("pactffi_write_pact_file", "int32", ["int32", "string", "uint8"]),
  pactffi_mock_server_logs: lib.func("pactffi_mock_server_logs", "string", ["int32"]),
  pactffi_generate_datetime_string: lib.func("pactffi_generate_datetime_string", "string", ["string"]),
  pactffi_check_regex: lib.func("pactffi_check_regex", "uint8", ["string", "string"]),
  pactffi_generate_regex_value: lib.func("pactffi_generate_regex_value", "string", ["string"]),
  pactffi_free_string: lib.func("pactffi_free_string", "void", ["string"]),
  pactffi_new_pact: lib.func("pactffi_new_pact", "uint16", ["string", "string"]),
  pactffi_new_interaction: lib.func("pactffi_new_interaction", "uint32", ["uint16", "string"]),
  pactffi_new_message_interaction: lib.func("pactffi_new_message_interaction", "uint32", ["uint16", "string"]),
  pactffi_new_sync_message_interaction: lib.func("pactffi_new_sync_message_interaction", "uint32", ["uint16", "string"]),
  pactffi_upon_receiving: lib.func("pactffi_upon_receiving", "uint8", ["uint32", "string"]),
  pactffi_given: lib.func("pactffi_given", "uint8", ["uint32", "string"]),
  pactffi_interaction_test_name: lib.func("pactffi_interaction_test_name", "uint32", ["uint32", "string"]),
  pactffi_given_with_param: lib.func("pactffi_given_with_param", "uint8", ["uint32", "string", "string", "string"]),
  pactffi_with_request: lib.func("pactffi_with_request", "uint8", ["uint32", "string", "string"]),
  pactffi_with_query_parameter: lib.func("pactffi_with_query_parameter", "uint8", ["uint32", "string", "size_t", "string"]),
  pactffi_with_query_parameter_v2: lib.func("pactffi_with_query_parameter_v2", "uint8", ["uint32", "string", "size_t", "string"]),
  pactffi_with_specification: lib.func("pactffi_with_specification", "uint8", ["uint16", "int32"]),
  pactffi_with_pact_metadata: lib.func("pactffi_with_pact_metadata", "uint8", ["uint16", "string", "string", "string"]),
  pactffi_with_header: lib.func("pactffi_with_header", "uint8", ["uint32", "int32", "string", "size_t", "string"]),
  pactffi_with_header_v2: lib.func("pactffi_with_header_v2", "uint8", ["uint32", "int32", "string", "size_t", "string"]),
  pactffi_response_status: lib.func("pactffi_response_status", "uint8", ["uint32", "uint16"]),
  pactffi_with_body: lib.func("pactffi_with_body", "uint8", ["uint32", "int32", "string", "string"]),
  pactffi_with_binary_file: lib.func("pactffi_with_binary_file", "uint8", ["uint32", "int32", "string", "string", "size_t"]),
  pactffi_with_multipart_file: lib.func("pactffi_with_multipart_file", "string", ["uint32", "int32", "string", "string", "string"]),
  pactffi_pact_handle_get_message_iter: lib.func("pactffi_pact_handle_get_message_iter", "string", ["uint16"]),
  pactffi_pact_handle_get_sync_message_iter: lib.func("pactffi_pact_handle_get_sync_message_iter", "string", ["uint16"]),
  pactffi_pact_handle_get_sync_http_iter: lib.func("pactffi_pact_handle_get_sync_http_iter", "string", ["uint16"]),
  pactffi_new_message_pact: lib.func("pactffi_new_message_pact", "uint16", ["string", "string"]),
  pactffi_new_message: lib.func("pactffi_new_message", "uint32", ["uint16", "string"]),
  pactffi_message_expects_to_receive: lib.func("pactffi_message_expects_to_receive", "void", ["uint32", "string"]),
  pactffi_message_given: lib.func("pactffi_message_given", "void", ["uint32", "string"]),
  pactffi_message_given_with_param: lib.func("pactffi_message_given_with_param", "void", ["uint32", "string", "string", "string"]),
  pactffi_message_with_contents: lib.func("pactffi_message_with_contents", "void", ["uint32", "string", "string", "size_t"]),
  pactffi_message_with_metadata: lib.func("pactffi_message_with_metadata", "void", ["uint32", "string", "string"]),
  pactffi_message_reify: lib.func("pactffi_message_reify", "string", ["uint32"]),
  pactffi_write_message_pact_file: lib.func("pactffi_write_message_pact_file", "int32", ["uint16", "string", "uint8"]),
  pactffi_with_message_pact_metadata: lib.func("pactffi_with_message_pact_metadata", "void", ["uint16", "string", "string", "string"]),
  pactffi_pact_handle_write_file: lib.func("pactffi_pact_handle_write_file", "int32", ["uint16", "string", "uint8"]),
  pactffi_new_async_message: lib.func("pactffi_new_async_message", "uint32", ["uint16", "string"]),
  pactffi_free_pact_handle: lib.func("pactffi_free_pact_handle", "uint32", ["uint16"]),
  pactffi_free_message_pact_handle: lib.func("pactffi_free_message_pact_handle", "uint32", ["uint16"]),
  pactffi_verify: lib.func("pactffi_verify", "int32", ["string"]),
  pactffi_verifier_new: lib.func("pactffi_verifier_new", "string", []),
  pactffi_verifier_new_for_application: lib.func("pactffi_verifier_new_for_application", "string", ["string", "string"]),
  pactffi_verifier_shutdown: lib.func("pactffi_verifier_shutdown", "void", ["string"]),
  pactffi_verifier_set_provider_info: lib.func("pactffi_verifier_set_provider_info", "void", ["string", "string", "string", "string", "uint16", "string"]),
  pactffi_verifier_add_provider_transport: lib.func("pactffi_verifier_add_provider_transport", "void", ["string", "string", "uint16", "string", "string"]),
  pactffi_verifier_set_filter_info: lib.func("pactffi_verifier_set_filter_info", "void", ["string", "string", "string", "uint8"]),
  pactffi_verifier_set_provider_state: lib.func("pactffi_verifier_set_provider_state", "void", ["string", "string", "uint8", "uint8"]),
  pactffi_verifier_set_verification_options: lib.func("pactffi_verifier_set_verification_options", "int32", ["string", "uint8", "uint64"]),
  pactffi_verifier_set_coloured_output: lib.func("pactffi_verifier_set_coloured_output", "int32", ["string", "uint8"]),
  pactffi_verifier_set_no_pacts_is_error: lib.func("pactffi_verifier_set_no_pacts_is_error", "int32", ["string", "uint8"]),
  pactffi_verifier_set_publish_options: lib.func("pactffi_verifier_set_publish_options", "int32", ["string", "string", "string", "string", "uint16", "string"]),
  pactffi_verifier_set_consumer_filters: lib.func("pactffi_verifier_set_consumer_filters", "void", ["string", "string", "uint16"]),
  pactffi_verifier_add_custom_header: lib.func("pactffi_verifier_add_custom_header", "void", ["string", "string", "string"]),
  pactffi_verifier_add_file_source: lib.func("pactffi_verifier_add_file_source", "void", ["string", "string"]),
  pactffi_verifier_add_directory_source: lib.func("pactffi_verifier_add_directory_source", "void", ["string", "string"]),
  pactffi_verifier_url_source: lib.func("pactffi_verifier_url_source", "void", ["string", "string", "string", "string", "string"]),
  pactffi_verifier_broker_source: lib.func("pactffi_verifier_broker_source", "void", ["string", "string", "string", "string", "string"]),
  pactffi_verifier_broker_source_with_selectors: lib.func("pactffi_verifier_broker_source_with_selectors", "void", ["string", "string", "string", "string", "string", "uint8", "string", "string", "uint16", "string", "string", "uint16", "string", "uint16"]),
  pactffi_verifier_execute: lib.func("pactffi_verifier_execute", "int32", ["string"]),
  pactffi_verifier_cli_args: lib.func("pactffi_verifier_cli_args", "string", []),
  pactffi_verifier_logs: lib.func("pactffi_verifier_logs", "string", ["string"]),
  pactffi_verifier_logs_for_provider: lib.func("pactffi_verifier_logs_for_provider", "string", ["string"]),
  pactffi_verifier_output: lib.func("pactffi_verifier_output", "string", ["string", "uint8"]),
  pactffi_verifier_json: lib.func("pactffi_verifier_json", "string", ["string"]),
  pactffi_using_plugin: lib.func("pactffi_using_plugin", "uint32", ["uint16", "string", "string"]),
  pactffi_cleanup_plugins: lib.func("pactffi_cleanup_plugins", "void", ["uint16"]),
  pactffi_interaction_contents: lib.func("pactffi_interaction_contents", "uint32", ["uint32", "int32", "string", "string"]),
  pactffi_matches_string_value: lib.func("pactffi_matches_string_value", "string", ["string", "string", "string", "uint8"]),
  pactffi_matches_u64_value: lib.func("pactffi_matches_u64_value", "string", ["string", "uint64", "uint64", "uint8"]),
  pactffi_matches_i64_value: lib.func("pactffi_matches_i64_value", "string", ["string", "int64", "int64", "uint8"]),
  pactffi_matches_f64_value: lib.func("pactffi_matches_f64_value", "string", ["string", "double", "double", "uint8"]),
  pactffi_matches_bool_value: lib.func("pactffi_matches_bool_value", "string", ["string", "uint8", "uint8", "uint8"]),
  pactffi_matches_binary_value: lib.func("pactffi_matches_binary_value", "string", ["string", "string", "uint64", "string", "uint64", "uint8"]),
  pactffi_matches_json_value: lib.func("pactffi_matches_json_value", "string", ["string", "string", "string", "uint8"])
      
    }
  }
console.log(`Hello Ffi!\n ${PactFfiLib().pactffi_version()}`);  